export type Diet = 'vegetarian' | 'vegan' | 'keto' | 'none';
export type Cuisine = 'german' | 'italian' | 'indian' | 'japanese' | 'gourmet' | 'fusion';

export interface SeedIngredient {
  name: string;
  quantity: number;
  unit: string;
  isFromUser: boolean;
  isOptional?: boolean;
}

export interface SeedStep {
  order: number;
  text: string;
  durationMinutes?: number;
  parallelGroup?: string;
  assignedToHelper: 1 | 2 | 3 | 4; 
}

export interface SeedNutrition {
  energyKcalPerPortion: number;
  proteinGramsPerPortion: number;
  fatGramsPerPortion: number;
  carbsGramsPerPortion: number;
}

export interface FirestoreRecipe {
  id: string;
  title: string;
  description?: string;
  diet: Diet;
  totalMinutes: number;
  cuisine: Cuisine;
  ingredients: SeedIngredient[];
  steps: SeedStep[];
  nutrition?: SeedNutrition;
  likes: number;
  source: 'ai' | 'seed';
  createdAt: any;
}

export const SEED_RECIPES: FirestoreRecipe[] = [

  {
    id: 'seed-japanese-teriyaki-chicken-bowl-1',
    title: 'Teriyaki Chicken Rice Bowl',
    description: 'Pan-seared chicken in teriyaki sauce served over warm rice.',
    diet: 'none',
    totalMinutes: 30,
    cuisine: 'japanese',
    likes: 63,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Chicken thighs, bite-size pieces', quantity: 350, unit: 'g', isFromUser: true },
    { name: 'Cooked white rice', quantity: 300, unit: 'g', isFromUser: true },
    { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: true, isOptional: true },
    { name: 'Soy sauce', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Sugar', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Garlic clove, grated', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Fresh ginger, grated', quantity: 1, unit: 'tsp', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Pat the chicken pieces dry, season lightly and let them sit while you prepare the sauce.', durationMinutes: 5, assignedToHelper: 1 },
    { order: 2, text: 'Mix soy sauce, mirin and sugar with grated garlic and ginger in a small bowl until the sugar dissolves.', durationMinutes: 4, assignedToHelper: 2 },
    { order: 3, text: 'Sear chicken in a hot pan until the pieces are browned on both sides and almost cooked through.', durationMinutes: 8, assignedToHelper: 3 },
    { order: 4, text: 'Pour the sauce over the chicken and simmer until it thickens into a glossy coating.', durationMinutes: 6, assignedToHelper: 4 },
    { order: 5, text: 'Serve the teriyaki chicken over bowls of warm rice and finish with sliced spring onions.', durationMinutes: 7, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 720,
    proteinGramsPerPortion: 35,
    fatGramsPerPortion: 24,
    carbsGramsPerPortion: 88,
    },
    },
    
    {
    id: 'seed-japanese-salmon-teriyaki-2',
    title: 'Salmon Teriyaki with Broccoli',
    description: 'Oven-baked teriyaki salmon served with steamed broccoli and rice.',
    diet: 'none',
    totalMinutes: 30,
    cuisine: 'japanese',
    likes: 55,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Salmon fillets', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Broccoli florets', quantity: 200, unit: 'g', isFromUser: true },
    { name: 'Cooked white rice', quantity: 250, unit: 'g', isFromUser: true },
    { name: 'Soy sauce', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Honey', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Sesame seeds', quantity: 1, unit: 'tsp', isFromUser: true, isOptional: true },
    ],
    steps: [
    { order: 1, text: 'Whisk soy sauce, mirin and honey into a smooth marinade in a small bowl.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Place salmon fillets in a baking dish, spoon over the marinade and let them sit briefly.', durationMinutes: 6, assignedToHelper: 2 },
    { order: 3, text: 'Bake the salmon in a hot oven until just cooked and the surface looks glazed.', durationMinutes: 12, assignedToHelper: 3 },
    { order: 4, text: 'Steam broccoli florets in lightly salted water until just tender but still bright green.', durationMinutes: 6, assignedToHelper: 4 },
    { order: 5, text: 'Serve salmon pieces over rice with broccoli on the side and sprinkle with sesame seeds.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 650,
    proteinGramsPerPortion: 34,
    fatGramsPerPortion: 22,
    carbsGramsPerPortion: 76,
    },
    },
    
    {
    id: 'seed-japanese-chicken-katsu-curry-3',
    title: 'Chicken Katsu Curry',
    description: 'Crispy breaded chicken cutlet with mild Japanese curry sauce.',
    diet: 'none',
    totalMinutes: 45,
    cuisine: 'japanese',
    likes: 78,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Chicken breast, flattened', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Onion, sliced', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Carrot, chunks', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Potato, chunks', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Japanese curry roux cubes', quantity: 2, unit: 'pcs', isFromUser: false },
    { name: 'Panko breadcrumbs', quantity: 60, unit: 'g', isFromUser: true },
    { name: 'Egg, beaten', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Oil for frying', quantity: 300, unit: 'ml', isFromUser: false },
    { name: 'Cooked white rice', quantity: 280, unit: 'g', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Simmer onion, carrot and potato in water until just tender and ready for the curry roux.', durationMinutes: 15, assignedToHelper: 1 },
    { order: 2, text: 'Stir curry roux cubes into the hot vegetable pot until fully dissolved and thickened.', durationMinutes: 8, assignedToHelper: 2 },
    { order: 3, text: 'Coat chicken in beaten egg, then press into panko until the surface is well covered.', durationMinutes: 8, assignedToHelper: 3 },
    { order: 4, text: 'Deep-fry or shallow-fry the coated chicken until golden and cooked through inside.', durationMinutes: 10, assignedToHelper: 4 },
    { order: 5, text: 'Slice the katsu, arrange it over rice and spoon hot curry sauce over one side.', durationMinutes: 4, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 900,
    proteinGramsPerPortion: 40,
    fatGramsPerPortion: 42,
    carbsGramsPerPortion: 92,
    },
    },
    
    {
    id: 'seed-japanese-vegetable-curry-rice-4',
    title: 'Vegetable Japanese Curry Rice',
    description: 'Mild Japanese curry packed with vegetables served over rice.',
    diet: 'vegan',
    totalMinutes: 40,
    cuisine: 'japanese',
    likes: 49,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Onion, sliced', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Carrots, chunks', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Potatoes, chunks', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Green peas, frozen', quantity: 80, unit: 'g', isFromUser: true },
    { name: 'Japanese curry roux cubes (vegan)', quantity: 2, unit: 'pcs', isFromUser: false },
    { name: 'Vegetable stock or water', quantity: 700, unit: 'ml', isFromUser: false },
    { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Cooked white rice', quantity: 280, unit: 'g', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Heat oil in a pot and sauté the sliced onion until it turns soft and lightly golden.', durationMinutes: 7, assignedToHelper: 1 },
    { order: 2, text: 'Add carrot and potato chunks, stir to coat them briefly in the onions and oil.', durationMinutes: 4, assignedToHelper: 2 },
    { order: 3, text: 'Pour in stock, bring to a gentle boil and cook until the vegetables are tender.', durationMinutes: 15, assignedToHelper: 3 },
    { order: 4, text: 'Turn off the heat, stir in the curry roux cubes until dissolved, then simmer to thicken.', durationMinutes: 8, assignedToHelper: 4 },
    { order: 5, text: 'Stir in peas at the end and serve the curry over bowls of hot rice.', durationMinutes: 6, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 680,
    proteinGramsPerPortion: 14,
    fatGramsPerPortion: 18,
    carbsGramsPerPortion: 112,
    },
    },
    
    {
    id: 'seed-japanese-miso-soup-tofu-5',
    title: 'Miso Soup with Tofu and Wakame',
    description: 'Light miso soup with tofu cubes, wakame and spring onions.',
    diet: 'vegan',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 42,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Soft tofu, cubes', quantity: 150, unit: 'g', isFromUser: true },
    { name: 'Dried wakame seaweed', quantity: 5, unit: 'g', isFromUser: true },
    { name: 'Spring onions, finely sliced', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Dashi stock (vegan if needed)', quantity: 800, unit: 'ml', isFromUser: false },
    { name: 'Miso paste', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Cooked white rice', quantity: 200, unit: 'g', isFromUser: true, isOptional: true },
    ],
    steps: [
    { order: 1, text: 'Soak dried wakame in a small bowl of water until it softens and expands.', durationMinutes: 5, assignedToHelper: 1 },
    { order: 2, text: 'Warm dashi stock in a pot, keeping it just below boiling to protect the miso flavor.', durationMinutes: 5, assignedToHelper: 2 },
    { order: 3, text: 'Stir miso paste into a ladle of warm stock, then return it to the pot and mix well.', durationMinutes: 4, assignedToHelper: 3 },
    { order: 4, text: 'Add tofu cubes and drained wakame and heat gently so the soup stays hot but not boiling.', durationMinutes: 4, assignedToHelper: 4 },
    { order: 5, text: 'Serve in small bowls and scatter sliced spring onions on top, with rice on the side if you like.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 220,
    proteinGramsPerPortion: 14,
    fatGramsPerPortion: 8,
    carbsGramsPerPortion: 22,
    },
    },
    
    {
    id: 'seed-japanese-yakisoba-stirfry-6',
    title: 'Yakisoba Noodle Stir-Fry',
    description: 'Stir-fried wheat noodles with pork strips and vegetables in yakisoba sauce.',
    diet: 'none',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 61,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Yakisoba or wheat noodles', quantity: 300, unit: 'g', isFromUser: true },
    { name: 'Pork belly or shoulder, strips', quantity: 200, unit: 'g', isFromUser: true },
    { name: 'White cabbage, shredded', quantity: 150, unit: 'g', isFromUser: true },
    { name: 'Carrot, thin strips', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Onion, sliced', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Yakisoba sauce or thick Worcestershire sauce', quantity: 4, unit: 'tbsp', isFromUser: false },
    { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Loosen the noodles with a little hot water if needed so they separate easily.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Heat oil in a large pan and fry pork strips until they start to brown at the edges.', durationMinutes: 6, assignedToHelper: 2 },
    { order: 3, text: 'Add onion, cabbage and carrot and stir-fry until the vegetables soften slightly.', durationMinutes: 6, assignedToHelper: 3 },
    { order: 4, text: 'Add the noodles and yakisoba sauce, tossing until everything is evenly coated and hot.', durationMinutes: 7, assignedToHelper: 4 },
    { order: 5, text: 'Serve the yakisoba straight from the pan while it is still sizzling.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 710,
    proteinGramsPerPortion: 27,
    fatGramsPerPortion: 28,
    carbsGramsPerPortion: 86,
    },
    },
    
    {
    id: 'seed-japanese-oyakodon-chicken-egg-7',
    title: 'Oyako Chicken Egg Donburi',
    description: 'Chicken and onion simmered in dashi with egg over rice.',
    diet: 'none',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 59,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Chicken thigh, thin slices', quantity: 220, unit: 'g', isFromUser: true },
    { name: 'Onion, thinly sliced', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Eggs, lightly beaten', quantity: 3, unit: 'pcs', isFromUser: true },
    { name: 'Cooked white rice', quantity: 280, unit: 'g', isFromUser: true },
    { name: 'Dashi stock', quantity: 200, unit: 'ml', isFromUser: false },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 1.5, unit: 'tbsp', isFromUser: false },
    { name: 'Spring onions, sliced', quantity: 1, unit: 'pcs', isFromUser: true, isOptional: true },
    ],
    steps: [
    { order: 1, text: 'Simmer dashi, soy sauce and mirin in a small pan to create a light sweet broth.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Add sliced onion and cook until it softens and becomes translucent.', durationMinutes: 5, assignedToHelper: 2 },
    { order: 3, text: 'Lay chicken slices on top, cover and simmer gently until just cooked through.', durationMinutes: 7, assignedToHelper: 3 },
    { order: 4, text: 'Pour beaten eggs evenly over the chicken and cover until the egg is softly set.', durationMinutes: 5, assignedToHelper: 4 },
    { order: 5, text: 'Slide the mixture over bowls of hot rice and garnish with spring onions.', durationMinutes: 4, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 650,
    proteinGramsPerPortion: 34,
    fatGramsPerPortion: 20,
    carbsGramsPerPortion: 78,
    },
    },
    
    {
    id: 'seed-japanese-gyudon-beef-bowl-8',
    title: 'Gyudon Beef Rice Bowl',
    description: 'Thinly sliced beef and onions simmered in sweet soy over rice.',
    diet: 'none',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 67,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Thinly sliced beef', quantity: 250, unit: 'g', isFromUser: true },
    { name: 'Onion, thinly sliced', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Cooked white rice', quantity: 280, unit: 'g', isFromUser: true },
    { name: 'Dashi stock', quantity: 200, unit: 'ml', isFromUser: false },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Sugar', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Pickled ginger', quantity: 1, unit: 'tbsp', isFromUser: true, isOptional: true },
    ],
    steps: [
    { order: 1, text: 'Combine dashi, soy sauce, mirin and sugar in a pan and bring to a gentle simmer.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Add sliced onions and cook until they soften and absorb some of the broth.', durationMinutes: 6, assignedToHelper: 2 },
    { order: 3, text: 'Spread the beef slices into the pan, separating them so they cook evenly.', durationMinutes: 5, assignedToHelper: 3 },
    { order: 4, text: 'Simmer briefly until the beef is just cooked and still tender in the sweet sauce.', durationMinutes: 5, assignedToHelper: 4 },
    { order: 5, text: 'Serve the beef and onions over rice and add pickled ginger on top if you like.', durationMinutes: 5, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 720,
    proteinGramsPerPortion: 33,
    fatGramsPerPortion: 24,
    carbsGramsPerPortion: 90,
    },
    },
    
    {
    id: 'seed-japanese-tofu-vegetable-don-9',
    title: 'Tofu and Vegetable Donburi',
    description: 'Pan-fried tofu and mixed vegetables glazed in soy sauce over rice.',
    diet: 'vegan',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 40,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Firm tofu, cubes', quantity: 220, unit: 'g', isFromUser: true },
    { name: 'Broccoli florets', quantity: 120, unit: 'g', isFromUser: true },
    { name: 'Carrot, thin slices', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'White cabbage, shredded', quantity: 80, unit: 'g', isFromUser: true },
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    { name: 'Soy sauce', quantity: 2.5, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin or rice syrup', quantity: 1.5, unit: 'tbsp', isFromUser: false },
    { name: 'Sesame oil', quantity: 1, unit: 'tsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Pat tofu dry and sear the cubes in a pan until all sides are lightly golden.', durationMinutes: 7, assignedToHelper: 1 },
    { order: 2, text: 'Add broccoli, carrot and cabbage to the pan and stir-fry until just tender.', durationMinutes: 7, assignedToHelper: 2 },
    { order: 3, text: 'Mix soy sauce, mirin and sesame oil, then pour the mixture over the tofu and vegetables.', durationMinutes: 3, assignedToHelper: 3 },
    { order: 4, text: 'Let the sauce bubble briefly so it reduces and coats everything in a shiny layer.', durationMinutes: 4, assignedToHelper: 4 },
    { order: 5, text: 'Serve the tofu and vegetables over hot rice and spoon leftover sauce on top.', durationMinutes: 4, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 620,
    proteinGramsPerPortion: 21,
    fatGramsPerPortion: 18,
    carbsGramsPerPortion: 90,
    },
    },
    
    {
    id: 'seed-japanese-onigiri-plate-10',
    title: 'Onigiri Rice Plate with Cucumber',
    description: 'Simple rice balls with filling, served with cucumber sticks.',
    diet: 'none',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 34,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Cooked Japanese rice', quantity: 320, unit: 'g', isFromUser: true },
    { name: 'Canned tuna, drained', quantity: 80, unit: 'g', isFromUser: true },
    { name: 'Mayonnaise', quantity: 2, unit: 'tbsp', isFromUser: true },
    { name: 'Cucumber, sticks', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Nori sheets, strips', quantity: 2, unit: 'pcs', isFromUser: true, isOptional: true },
    { name: 'Soy sauce', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Salt', quantity: 0.25, unit: 'tsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Mix drained tuna with mayonnaise and a few drops of soy sauce to make a moist filling.', durationMinutes: 5, assignedToHelper: 1 },
    { order: 2, text: 'Season warm rice lightly with salt and let it cool just enough to handle.', durationMinutes: 6, assignedToHelper: 2 },
    { order: 3, text: 'Wet your hands, place some rice on your palm, add tuna filling and shape into firm triangles.', durationMinutes: 8, assignedToHelper: 3 },
    { order: 4, text: 'Wrap a strip of nori around each onigiri if you are using seaweed.', durationMinutes: 3, assignedToHelper: 4 },
    { order: 5, text: 'Serve the onigiri on a plate with cucumber sticks and a small dish of soy sauce.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 540,
    proteinGramsPerPortion: 18,
    fatGramsPerPortion: 15,
    carbsGramsPerPortion: 80,
    },
    },
    
    {
    id: 'seed-japanese-tamagoyaki-rice-11',
    title: 'Tamagoyaki Omelette with Rice',
    description: 'Rolled Japanese omelette served with rice and cucumber.',
    diet: 'none',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 39,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Eggs', quantity: 4, unit: 'pcs', isFromUser: true },
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    { name: 'Cucumber, thin slices', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Sugar', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Soy sauce', quantity: 1, unit: 'tsp', isFromUser: false },
    { name: 'Dashi or water', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Oil for frying', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Whisk eggs with sugar, soy sauce and dashi until the mixture looks smooth.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Heat a little oil in a small pan and pour in a thin layer of egg mixture.', durationMinutes: 4, assignedToHelper: 2 },
    { order: 3, text: 'Roll the set egg to one side, add more egg mixture and repeat to build layers.', durationMinutes: 7, assignedToHelper: 3 },
    { order: 4, text: 'Let the rolled omelette cool slightly, then slice it into neat pieces.', durationMinutes: 3, assignedToHelper: 4 },
    { order: 5, text: 'Serve the tamagoyaki slices with rice and cucumber on the side.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 520,
    proteinGramsPerPortion: 22,
    fatGramsPerPortion: 20,
    carbsGramsPerPortion: 62,
    },
    },
    
    {
    id: 'seed-japanese-chicken-udon-soup-12',
    title: 'Chicken Udon Noodle Soup',
    description: 'Udon noodles in a light chicken dashi broth with vegetables.',
    diet: 'none',
    totalMinutes: 30,
    cuisine: 'japanese',
    likes: 48,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Udon noodles, fresh', quantity: 300, unit: 'g', isFromUser: true },
    { name: 'Chicken breast, thin strips', quantity: 200, unit: 'g', isFromUser: true },
    { name: 'Carrot, julienne', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Dashi stock', quantity: 900, unit: 'ml', isFromUser: false },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Bring dashi to a simmer and season it with soy sauce and mirin to taste.', durationMinutes: 5, assignedToHelper: 1 },
    { order: 2, text: 'Add chicken strips to the broth and cook until they are just opaque.', durationMinutes: 7, assignedToHelper: 2 },
    { order: 3, text: 'Stir in carrots and let them soften slightly while the broth stays hot.', durationMinutes: 5, assignedToHelper: 3 },
    { order: 4, text: 'Cook udon noodles separately according to the packet, then drain them.', durationMinutes: 8, assignedToHelper: 4 },
    { order: 5, text: 'Place noodles in bowls, pour hot soup over them and top with spring onions.', durationMinutes: 5, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 620,
    proteinGramsPerPortion: 29,
    fatGramsPerPortion: 11,
    carbsGramsPerPortion: 98,
    },
    },
    
    {
    id: 'seed-japanese-veggie-yaki-udon-13',
    title: 'Vegetable Yaki Udon',
    description: 'Stir-fried udon noodles with mixed vegetables in soy sauce.',
    diet: 'vegan',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 36,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Udon noodles, fresh', quantity: 300, unit: 'g', isFromUser: true },
    { name: 'White cabbage, shredded', quantity: 120, unit: 'g', isFromUser: true },
    { name: 'Carrot, julienne', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Mushrooms, sliced', quantity: 120, unit: 'g', isFromUser: true },
    { name: 'Soy sauce', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Sesame oil', quantity: 1, unit: 'tsp', isFromUser: false },
    { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Loosen udon noodles with hot water so they separate without breaking.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Heat oil in a large pan and fry mushrooms and carrot until lightly browned.', durationMinutes: 6, assignedToHelper: 2 },
    { order: 3, text: 'Add cabbage and stir-fry until it softens but still keeps a little crunch.', durationMinutes: 5, assignedToHelper: 3 },
    { order: 4, text: 'Add noodles, soy sauce and sesame oil, tossing until everything is hot and coated.', durationMinutes: 7, assignedToHelper: 4 },
    { order: 5, text: 'Serve the yaki udon straight from the pan on warm plates.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 610,
    proteinGramsPerPortion: 16,
    fatGramsPerPortion: 18,
    carbsGramsPerPortion: 96,
    },
    },
    
    {
    id: 'seed-japanese-cold-soba-dip-14',
    title: 'Cold Soba with Dipping Sauce',
    description: 'Chilled buckwheat noodles served with soy-based dipping sauce.',
    diet: 'vegan',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 33,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Dried soba noodles', quantity: 220, unit: 'g', isFromUser: true },
    { name: 'Spring onions, finely sliced', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Grated daikon or radish', quantity: 40, unit: 'g', isFromUser: true, isOptional: true },
    { name: 'Soy sauce', quantity: 4, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Water', quantity: 150, unit: 'ml', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Cook soba noodles in boiling water until just tender, then rinse well under cold water.', durationMinutes: 9, assignedToHelper: 1 },
    { order: 2, text: 'Drain the noodles thoroughly and leave them to chill in a colander.', durationMinutes: 4, assignedToHelper: 2 },
    { order: 3, text: 'Mix soy sauce, mirin and water in a small jug to make a dipping broth.', durationMinutes: 3, assignedToHelper: 3 },
    { order: 4, text: 'Arrange cold soba in serving bowls or on a tray in small bundles.', durationMinutes: 2, assignedToHelper: 4 },
    { order: 5, text: 'Serve with dipping sauce, spring onions and grated radish on the side.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 420,
    proteinGramsPerPortion: 15,
    fatGramsPerPortion: 4,
    carbsGramsPerPortion: 80,
    },
    },
    
    {
    id: 'seed-japanese-miso-glazed-eggplant-15',
    title: 'Miso Glazed Eggplant',
    description: 'Roasted eggplant halves topped with sweet miso glaze.',
    diet: 'vegan',
    totalMinutes: 30,
    cuisine: 'japanese',
    likes: 37,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Eggplant, halved lengthwise', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Spring onions, sliced', quantity: 1, unit: 'pcs', isFromUser: true, isOptional: true },
    { name: 'White miso paste', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 1.5, unit: 'tbsp', isFromUser: false },
    { name: 'Sugar', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Sesame oil', quantity: 1, unit: 'tsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Score the flesh of each eggplant half in a criss-cross pattern without cutting through the skin.', durationMinutes: 5, assignedToHelper: 1 },
    { order: 2, text: 'Roast the eggplants cut side up until the flesh is soft and starting to brown.', durationMinutes: 15, assignedToHelper: 2 },
    { order: 3, text: 'Mix miso, mirin, sugar and sesame oil into a thick glossy paste.', durationMinutes: 4, assignedToHelper: 3 },
    { order: 4, text: 'Spread the miso mixture over the cut surface of the hot eggplants.', durationMinutes: 3, assignedToHelper: 4 },
    { order: 5, text: 'Return to the oven briefly to caramelize, then finish with spring onions before serving.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 260,
    proteinGramsPerPortion: 6,
    fatGramsPerPortion: 11,
    carbsGramsPerPortion: 34,
    },
    },
    
    {
    id: 'seed-japanese-ginger-pork-shogayaki-16',
    title: 'Ginger Pork Shogayaki',
    description: 'Thin pork slices in a sweet ginger soy glaze served with rice.',
    diet: 'none',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 58,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Pork loin, thinly sliced', quantity: 240, unit: 'g', isFromUser: true },
    { name: 'White cabbage, fine shreds', quantity: 120, unit: 'g', isFromUser: true },
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    { name: 'Soy sauce', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Grated ginger', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Stir soy sauce, mirin and grated ginger together to create a punchy sauce.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Heat oil in a pan and fry the pork slices quickly until they lose their pink color.', durationMinutes: 6, assignedToHelper: 2 },
    { order: 3, text: 'Pour the sauce over the pork and cook until it thickens and coats the meat.', durationMinutes: 6, assignedToHelper: 3 },
    { order: 4, text: 'Pile shredded cabbage onto plates and spoon hot pork slices next to it.', durationMinutes: 5, assignedToHelper: 4 },
    { order: 5, text: 'Serve with bowls of steaming rice on the side.', durationMinutes: 4, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 680,
    proteinGramsPerPortion: 32,
    fatGramsPerPortion: 24,
    carbsGramsPerPortion: 86,
    },
    },
    
    {
    id: 'seed-japanese-karaage-chicken-17',
    title: 'Chicken Karaage Bites',
    description: 'Crispy marinated chicken bites with lemon and rice.',
    diet: 'none',
    totalMinutes: 35,
    cuisine: 'japanese',
    likes: 72,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Chicken thigh, bite-size chunks', quantity: 320, unit: 'g', isFromUser: true },
    { name: 'Garlic clove, grated', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Fresh ginger, grated', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Potato starch or cornstarch', quantity: 60, unit: 'g', isFromUser: true },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Oil for deep-frying', quantity: 400, unit: 'ml', isFromUser: false },
    { name: 'Lemon wedges', quantity: 4, unit: 'pcs', isFromUser: true, isOptional: true },
    ],
    steps: [
    { order: 1, text: 'Combine soy sauce, mirin, grated garlic and ginger in a bowl and add the chicken pieces.', durationMinutes: 6, assignedToHelper: 1 },
    { order: 2, text: 'Let the chicken marinate so the flavors can soak in and the meat softens slightly.', durationMinutes: 10, assignedToHelper: 2 },
    { order: 3, text: 'Coat each piece with starch, shaking off any heavy excess.', durationMinutes: 6, assignedToHelper: 3 },
    { order: 4, text: 'Fry the chicken in hot oil until the coating is crisp and the inside is cooked.', durationMinutes: 9, assignedToHelper: 4 },
    { order: 5, text: 'Serve the karaage with lemon wedges and rice or salad.', durationMinutes: 4, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 780,
    proteinGramsPerPortion: 34,
    fatGramsPerPortion: 47,
    carbsGramsPerPortion: 47,
    },
    },
    
    {
    id: 'seed-japanese-panko-fish-cabbage-18',
    title: 'Panko Fish with Cabbage Salad',
    description: 'Crispy panko-coated fish fillets with cabbage and rice.',
    diet: 'none',
    totalMinutes: 30,
    cuisine: 'japanese',
    likes: 44,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'White fish fillets', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Panko breadcrumbs', quantity: 60, unit: 'g', isFromUser: true },
    { name: 'Egg, beaten', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'White cabbage, shredded', quantity: 120, unit: 'g', isFromUser: true },
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    { name: 'Soy sauce', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Oil for frying', quantity: 250, unit: 'ml', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Season the fish lightly and dip it into beaten egg, then coat with panko crumbs.', durationMinutes: 7, assignedToHelper: 1 },
    { order: 2, text: 'Heat oil in a shallow pan and fry the fish until the crumb is golden and crisp.', durationMinutes: 8, assignedToHelper: 2 },
    { order: 3, text: 'Drain the fish briefly on paper so the excess oil is absorbed.', durationMinutes: 3, assignedToHelper: 3 },
    { order: 4, text: 'Toss shredded cabbage with a splash of soy sauce for a simple salad.', durationMinutes: 5, assignedToHelper: 4 },
    { order: 5, text: 'Serve the fish with cabbage and rice on the side.', durationMinutes: 7, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 680,
    proteinGramsPerPortion: 32,
    fatGramsPerPortion: 26,
    carbsGramsPerPortion: 78,
    },
    },
    
    {
    id: 'seed-japanese-tuna-mayo-donburi-19',
    title: 'Tuna Mayo Rice Donburi',
    description: 'Warm rice bowl topped with tuna mayonnaise and cucumber.',
    diet: 'none',
    totalMinutes: 15,
    cuisine: 'japanese',
    likes: 41,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Canned tuna, drained', quantity: 160, unit: 'g', isFromUser: true },
    { name: 'Mayonnaise', quantity: 3, unit: 'tbsp', isFromUser: true },
    { name: 'Cucumber, thin slices', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Cooked white rice', quantity: 280, unit: 'g', isFromUser: true },
    { name: 'Soy sauce', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Spring onions, sliced', quantity: 1, unit: 'pcs', isFromUser: true, isOptional: true },
    ],
    steps: [
    { order: 1, text: 'Combine drained tuna with mayonnaise and a small splash of soy sauce.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Stir the mixture until the tuna breaks into small flakes and is evenly coated.', durationMinutes: 3, assignedToHelper: 2 },
    { order: 3, text: 'Fill bowls with hot rice and smooth the surface gently with a spoon.', durationMinutes: 3, assignedToHelper: 3 },
    { order: 4, text: 'Spoon the tuna mixture on top and arrange cucumber slices around the edges.', durationMinutes: 3, assignedToHelper: 4 },
    { order: 5, text: 'Scatter spring onions over the bowl and serve immediately.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 630,
    proteinGramsPerPortion: 24,
    fatGramsPerPortion: 30,
    carbsGramsPerPortion: 64,
    },
    },
    
    {
    id: 'seed-japanese-potato-salad-20',
    title: 'Japanese Potato Salad',
    description: 'Creamy potato salad with cucumber, carrot and egg.',
    diet: 'vegetarian',
    totalMinutes: 30,
    cuisine: 'japanese',
    likes: 52,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Potatoes, peeled', quantity: 400, unit: 'g', isFromUser: true },
    { name: 'Carrot, small dice', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Cucumber, thin half-moons', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Eggs, boiled and chopped', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Mayonnaise', quantity: 4, unit: 'tbsp', isFromUser: true },
    { name: 'Rice vinegar', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Boil potatoes and carrot pieces in salted water until they are just tender.', durationMinutes: 15, assignedToHelper: 1 },
    { order: 2, text: 'Drain the vegetables and let the potatoes steam off excess moisture.', durationMinutes: 5, assignedToHelper: 2 },
    { order: 3, text: 'Mash potatoes roughly in a bowl, leaving some small chunks for texture.', durationMinutes: 4, assignedToHelper: 3 },
    { order: 4, text: 'Fold in carrot, cucumber, chopped egg, mayonnaise, vinegar and salt.', durationMinutes: 5, assignedToHelper: 4 },
    { order: 5, text: 'Chill briefly if possible, then serve the salad as a side dish.', durationMinutes: 1, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 430,
    proteinGramsPerPortion: 12,
    fatGramsPerPortion: 23,
    carbsGramsPerPortion: 44,
    },
    },
    
    {
    id: 'seed-japanese-spinach-gomae-rice-21',
    title: 'Spinach Goma-ae with Rice',
    description: 'Blanched spinach in sweet sesame dressing served with rice and egg.',
    diet: 'vegetarian',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 35,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Fresh spinach', quantity: 200, unit: 'g', isFromUser: true },
    { name: 'Sesame seeds', quantity: 2, unit: 'tbsp', isFromUser: true },
    { name: 'Sugar', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Soy sauce', quantity: 1.5, unit: 'tbsp', isFromUser: false },
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    { name: 'Egg, boiled and halved', quantity: 1, unit: 'pcs', isFromUser: true, isOptional: true },
    ],
    steps: [
    { order: 1, text: 'Blanch spinach briefly in boiling water until just wilted, then cool it in cold water.', durationMinutes: 5, assignedToHelper: 1 },
    { order: 2, text: 'Squeeze out excess water from the spinach and cut it into bite-size pieces.', durationMinutes: 4, assignedToHelper: 2 },
    { order: 3, text: 'Grind sesame seeds in a mortar, then mix with sugar and soy sauce to form a paste.', durationMinutes: 5, assignedToHelper: 3 },
    { order: 4, text: 'Toss the spinach thoroughly in the sesame dressing so all leaves are coated.', durationMinutes: 4, assignedToHelper: 4 },
    { order: 5, text: 'Serve spinach goma-ae beside rice and add egg halves on the plate.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 390,
    proteinGramsPerPortion: 14,
    fatGramsPerPortion: 11,
    carbsGramsPerPortion: 55,
    },
    },
    
    {
    id: 'seed-japanese-tofu-katsu-don-22',
    title: 'Crispy Tofu Katsu Don',
    description: 'Breaded tofu cutlets simmered in sauce and egg over rice.',
    diet: 'vegetarian',
    totalMinutes: 35,
    cuisine: 'japanese',
    likes: 47,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Firm tofu, thick slices', quantity: 220, unit: 'g', isFromUser: true },
    { name: 'Panko breadcrumbs', quantity: 60, unit: 'g', isFromUser: true },
    { name: 'Eggs, beaten', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Onion, thinly sliced', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    { name: 'Dashi stock', quantity: 150, unit: 'ml', isFromUser: false },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Sugar', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Oil for frying', quantity: 250, unit: 'ml', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Coat tofu slices in beaten egg, then press them into panko until well covered.', durationMinutes: 8, assignedToHelper: 1 },
    { order: 2, text: 'Fry the tofu in hot oil until the crust is crisp and pale golden.', durationMinutes: 8, assignedToHelper: 2 },
    { order: 3, text: 'Simmer dashi, soy sauce and sugar with sliced onion in a small pan.', durationMinutes: 7, assignedToHelper: 3 },
    { order: 4, text: 'Lay sliced tofu katsu into the pan, pour beaten egg around and cook until softly set.', durationMinutes: 7, assignedToHelper: 4 },
    { order: 5, text: 'Slide tofu and sauce over bowls of hot rice and serve immediately.', durationMinutes: 5, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 780,
    proteinGramsPerPortion: 26,
    fatGramsPerPortion: 38,
    carbsGramsPerPortion: 84,
    },
    },
    
    {
    id: 'seed-japanese-curry-udon-23',
    title: 'Japanese Curry Udon',
    description: 'Thick udon noodles in a mild curry soup with onions.',
    diet: 'none',
    totalMinutes: 30,
    cuisine: 'japanese',
    likes: 50,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Udon noodles, fresh', quantity: 300, unit: 'g', isFromUser: true },
    { name: 'Onion, thin slices', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Japanese curry roux cubes', quantity: 2, unit: 'pcs', isFromUser: false },
    { name: 'Dashi stock', quantity: 800, unit: 'ml', isFromUser: false },
    { name: 'Spring onions, sliced', quantity: 1, unit: 'pcs', isFromUser: true, isOptional: true },
    { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Sauté sliced onion in a little oil until it turns soft and lightly sweet.', durationMinutes: 6, assignedToHelper: 1 },
    { order: 2, text: 'Pour dashi into the pot with the onions and bring it to a gentle boil.', durationMinutes: 5, assignedToHelper: 2 },
    { order: 3, text: 'Turn off the heat, stir in curry roux cubes until dissolved, then simmer briefly.', durationMinutes: 7, assignedToHelper: 3 },
    { order: 4, text: 'Cook udon noodles separately, rinse quickly, then add them to the curry soup.', durationMinutes: 8, assignedToHelper: 4 },
    { order: 5, text: 'Serve the curry udon in deep bowls and top with sliced spring onions.', durationMinutes: 4, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 650,
    proteinGramsPerPortion: 17,
    fatGramsPerPortion: 15,
    carbsGramsPerPortion: 110,
    },
    },
    
    {
    id: 'seed-japanese-teriyaki-meatballs-24',
    title: 'Teriyaki Meatballs with Rice',
    description: 'Pan-glazed meatballs in teriyaki sauce served over rice.',
    diet: 'none',
    totalMinutes: 30,
    cuisine: 'japanese',
    likes: 46,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Ground beef or pork', quantity: 300, unit: 'g', isFromUser: true },
    { name: 'Onion, finely chopped', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Breadcrumbs', quantity: 30, unit: 'g', isFromUser: true },
    { name: 'Egg', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Soy sauce', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Sugar', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Mix meat with chopped onion, breadcrumbs, egg and a little salt until sticky.', durationMinutes: 7, assignedToHelper: 1 },
    { order: 2, text: 'Form small meatballs of even size and place them on a plate.', durationMinutes: 5, assignedToHelper: 2 },
    { order: 3, text: 'Brown the meatballs in a pan on all sides until almost cooked through.', durationMinutes: 8, assignedToHelper: 3 },
    { order: 4, text: 'Combine soy sauce, mirin and sugar, then pour into the pan to glaze the meatballs.', durationMinutes: 6, assignedToHelper: 4 },
    { order: 5, text: 'Serve the shiny meatballs over rice with extra sauce spooned on top.', durationMinutes: 4, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 780,
    proteinGramsPerPortion: 34,
    fatGramsPerPortion: 34,
    carbsGramsPerPortion: 86,
    },
    },
    
    {
    id: 'seed-japanese-salmon-rice-traybake-25',
    title: 'Salmon Rice Traybake',
    description: 'Baked salmon and vegetables on a bed of seasoned rice.',
    diet: 'none',
    totalMinutes: 35,
    cuisine: 'japanese',
    likes: 53,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Uncooked Japanese rice', quantity: 200, unit: 'g', isFromUser: true },
    { name: 'Salmon fillets', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Carrot, thin sticks', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Green beans, trimmed', quantity: 100, unit: 'g', isFromUser: true },
    { name: 'Dashi stock or water', quantity: 350, unit: 'ml', isFromUser: false },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Rinse the rice until the water runs mostly clear and drain it well.', durationMinutes: 6, assignedToHelper: 1 },
    { order: 2, text: 'Spread rice in a small baking dish and pour over dashi mixed with soy sauce and mirin.', durationMinutes: 5, assignedToHelper: 2 },
    { order: 3, text: 'Arrange salmon, carrot sticks and green beans on top of the rice.', durationMinutes: 5, assignedToHelper: 3 },
    { order: 4, text: 'Cover the dish with foil and bake until the rice is tender and salmon cooked through.', durationMinutes: 17, assignedToHelper: 4 },
    { order: 5, text: 'Fluff the rice gently and serve with pieces of salmon and vegetables on each plate.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 690,
    proteinGramsPerPortion: 33,
    fatGramsPerPortion: 18,
    carbsGramsPerPortion: 94,
    },
    },
    
    {
    id: 'seed-japanese-nikujaga-stew-26',
    title: 'Nikujaga Meat and Potato Stew',
    description: 'Classic Japanese stew of meat, potatoes and onions in sweet soy broth.',
    diet: 'none',
    totalMinutes: 45,
    cuisine: 'japanese',
    likes: 60,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Thinly sliced beef or pork', quantity: 250, unit: 'g', isFromUser: true },
    { name: 'Potatoes, chunks', quantity: 350, unit: 'g', isFromUser: true },
    { name: 'Onion, wedges', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Carrot, chunks', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Green beans, short pieces', quantity: 60, unit: 'g', isFromUser: true, isOptional: true },
    { name: 'Dashi stock', quantity: 500, unit: 'ml', isFromUser: false },
    { name: 'Soy sauce', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Sugar', quantity: 1.5, unit: 'tbsp', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Heat the dashi in a pot and dissolve sugar and soy sauce to create a seasoned broth.', durationMinutes: 5, assignedToHelper: 1 },
    { order: 2, text: 'Add potatoes, carrot and onion to the pot and bring everything to a gentle boil.', durationMinutes: 10, assignedToHelper: 2 },
    { order: 3, text: 'Simmer until the potatoes are nearly tender and flavors start to soak into the vegetables.', durationMinutes: 15, assignedToHelper: 3 },
    { order: 4, text: 'Add sliced meat and green beans, then cook until the meat is done and the sauce slightly reduced.', durationMinutes: 10, assignedToHelper: 4 },
    { order: 5, text: 'Let the stew rest a few minutes off the heat before serving it in deep bowls.', durationMinutes: 5, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 640,
    proteinGramsPerPortion: 28,
    fatGramsPerPortion: 20,
    carbsGramsPerPortion: 80,
    },
    },
    
    {
    id: 'seed-japanese-simmered-kabocha-27',
    title: 'Simmered Kabocha Pumpkin',
    description: 'Sweet soy simmered pumpkin cubes served warm or at room temperature.',
    diet: 'vegan',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 32,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Kabocha or hokkaido pumpkin, cubes', quantity: 400, unit: 'g', isFromUser: true },
    { name: 'Dashi stock or water', quantity: 300, unit: 'ml', isFromUser: false },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Sugar', quantity: 1.5, unit: 'tbsp', isFromUser: true },
    { name: 'Mirin', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Arrange pumpkin cubes in a single layer in a shallow pan.', durationMinutes: 3, assignedToHelper: 1 },
    { order: 2, text: 'Pour in dashi with soy sauce, sugar and mirin so the liquid almost covers the pumpkin.', durationMinutes: 4, assignedToHelper: 2 },
    { order: 3, text: 'Bring to a gentle simmer and cover the surface with a piece of baking paper.', durationMinutes: 4, assignedToHelper: 3 },
    { order: 4, text: 'Cook until the pumpkin is tender and the sauce has slightly reduced and thickened.', durationMinutes: 11, assignedToHelper: 4 },
    { order: 5, text: 'Serve warm or let cool to room temperature for a side dish.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 210,
    proteinGramsPerPortion: 4,
    fatGramsPerPortion: 1,
    carbsGramsPerPortion: 48,
    },
    },
    
    {
    id: 'seed-japanese-yaki-onigiri-miso-28',
    title: 'Yaki Onigiri with Miso Glaze',
    description: 'Grilled rice balls brushed with savory miso.',
    diet: 'vegan',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 38,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Cooked Japanese rice', quantity: 320, unit: 'g', isFromUser: true },
    { name: 'White miso paste', quantity: 1.5, unit: 'tbsp', isFromUser: false },
    { name: 'Soy sauce', quantity: 1, unit: 'tsp', isFromUser: false },
    { name: 'Sugar', quantity: 1, unit: 'tsp', isFromUser: true },
    { name: 'Oil for brushing pan', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Shape warm rice firmly into small flat triangles that hold together well.', durationMinutes: 7, assignedToHelper: 1 },
    { order: 2, text: 'Mix miso, soy sauce and sugar into a spreadable paste.', durationMinutes: 3, assignedToHelper: 2 },
    { order: 3, text: 'Heat a lightly oiled pan and grill the rice triangles until a crust forms on each side.', durationMinutes: 8, assignedToHelper: 3 },
    { order: 4, text: 'Brush the tops with miso mixture and grill briefly again without burning.', durationMinutes: 5, assignedToHelper: 4 },
    { order: 5, text: 'Serve the yaki onigiri hot as a snack or with soup.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 360,
    proteinGramsPerPortion: 8,
    fatGramsPerPortion: 4,
    carbsGramsPerPortion: 74,
    },
    },
    
    {
    id: 'seed-japanese-tofu-miso-stirfry-29',
    title: 'Tofu Miso Stir-Fry with Cabbage',
    description: 'Stir-fried tofu and cabbage in a savory miso sauce.',
    diet: 'vegan',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 37,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Firm tofu, cubes', quantity: 220, unit: 'g', isFromUser: true },
    { name: 'White cabbage, shredded', quantity: 150, unit: 'g', isFromUser: true },
    { name: 'Carrot, thin slices', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'White miso paste', quantity: 1.5, unit: 'tbsp', isFromUser: false },
    { name: 'Soy sauce', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Water', quantity: 60, unit: 'ml', isFromUser: false },
    { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Mix miso, soy sauce and water in a small bowl to create a loose sauce.', durationMinutes: 3, assignedToHelper: 1 },
    { order: 2, text: 'Heat oil in a pan and fry tofu cubes until lightly browned on several sides.', durationMinutes: 6, assignedToHelper: 2 },
    { order: 3, text: 'Add cabbage and carrot to the pan and stir-fry until they soften slightly.', durationMinutes: 5, assignedToHelper: 3 },
    { order: 4, text: 'Pour in the miso sauce and toss until the vegetables and tofu are coated.', durationMinutes: 4, assignedToHelper: 4 },
    { order: 5, text: 'Serve immediately with rice if desired.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 340,
    proteinGramsPerPortion: 18,
    fatGramsPerPortion: 16,
    carbsGramsPerPortion: 26,
    },
    },
    
    {
    id: 'seed-japanese-chicken-cabbage-stirfry-30',
    title: 'Ginger Chicken Cabbage Stir-Fry',
    description: 'Quick stir-fry of chicken and cabbage with ginger soy.',
    diet: 'none',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 43,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Chicken breast, thin strips', quantity: 220, unit: 'g', isFromUser: true },
    { name: 'White cabbage, shredded', quantity: 150, unit: 'g', isFromUser: true },
    { name: 'Carrot, thin strips', quantity: 1, unit: 'pcs', isFromUser: true },
    { name: 'Fresh ginger, grated', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Heat oil in a wide pan and add chicken strips in a single layer.', durationMinutes: 5, assignedToHelper: 1 },
    { order: 2, text: 'Cook the chicken until it starts to color and is almost done.', durationMinutes: 4, assignedToHelper: 2 },
    { order: 3, text: 'Add cabbage, carrot and grated ginger and stir-fry briskly.', durationMinutes: 5, assignedToHelper: 3 },
    { order: 4, text: 'Splash soy sauce around the pan and toss everything until glossy.', durationMinutes: 4, assignedToHelper: 4 },
    { order: 5, text: 'Serve the stir-fry over bowls of hot rice.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 610,
    proteinGramsPerPortion: 31,
    fatGramsPerPortion: 14,
    carbsGramsPerPortion: 86,
    },
    },
    
    {
    id: 'seed-japanese-soba-veggie-stirfry-31',
    title: 'Soba Vegetable Stir-Fry',
    description: 'Pan-fried soba noodles with mixed vegetables and soy.',
    diet: 'vegan',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 34,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Dried soba noodles', quantity: 220, unit: 'g', isFromUser: true },
    { name: 'Broccoli florets', quantity: 120, unit: 'g', isFromUser: true },
    { name: 'Bell pepper, strips', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Mushrooms, sliced', quantity: 100, unit: 'g', isFromUser: true },
    { name: 'Soy sauce', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Sesame oil', quantity: 1, unit: 'tsp', isFromUser: false },
    { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Cook soba noodles until just tender, then rinse under cold water and drain.', durationMinutes: 8, assignedToHelper: 1 },
    { order: 2, text: 'Heat oil in a pan and stir-fry broccoli, pepper and mushrooms until crisp-tender.', durationMinutes: 6, assignedToHelper: 2 },
    { order: 3, text: 'Add noodles to the pan and pour soy sauce and sesame oil over them.', durationMinutes: 3, assignedToHelper: 3 },
    { order: 4, text: 'Toss everything together until the noodles are hot and evenly coated.', durationMinutes: 3, assignedToHelper: 4 },
    { order: 5, text: 'Serve the soba stir-fry in deep bowls.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 520,
    proteinGramsPerPortion: 18,
    fatGramsPerPortion: 12,
    carbsGramsPerPortion: 82,
    },
    },
    
    {
    id: 'seed-japanese-teriyaki-tofu-skillet-32',
    title: 'Teriyaki Tofu Skillet',
    description: 'Pan-fried tofu cubes coated in glossy teriyaki sauce.',
    diet: 'vegan',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 39,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Firm tofu, cubes', quantity: 230, unit: 'g', isFromUser: true },
    { name: 'Spring onions, sliced', quantity: 1, unit: 'pcs', isFromUser: true, isOptional: true },
    { name: 'Soy sauce', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Mirin', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Sugar', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Mix soy sauce, mirin and sugar in a small bowl until the sugar dissolves.', durationMinutes: 3, assignedToHelper: 1 },
    { order: 2, text: 'Heat oil in a pan and fry tofu cubes until they develop a golden crust.', durationMinutes: 7, assignedToHelper: 2 },
    { order: 3, text: 'Pour the sauce into the pan and simmer until it thickens around the tofu.', durationMinutes: 6, assignedToHelper: 3 },
    { order: 4, text: 'Turn the tofu pieces so they are evenly coated in the glossy sauce.', durationMinutes: 2, assignedToHelper: 4 },
    { order: 5, text: 'Serve the tofu over rice and garnish with spring onions.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 610,
    proteinGramsPerPortion: 21,
    fatGramsPerPortion: 19,
    carbsGramsPerPortion: 88,
    },
    },
    
    {
    id: 'seed-japanese-salmon-sushi-bowl-33',
    title: 'Salmon Sushi Rice Bowl',
    description: 'Deconstructed sushi bowl with salmon, avocado and cucumber.',
    diet: 'none',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 62,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Cooked sushi rice', quantity: 280, unit: 'g', isFromUser: true },
    { name: 'Fresh salmon, small cubes', quantity: 180, unit: 'g', isFromUser: true },
    { name: 'Cucumber, small cubes', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Avocado, slices', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Rice vinegar', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Sesame seeds', quantity: 1, unit: 'tsp', isFromUser: true, isOptional: true },
    ],
    steps: [
    { order: 1, text: 'Season warm sushi rice lightly with rice vinegar and let it cool to lukewarm.', durationMinutes: 7, assignedToHelper: 1 },
    { order: 2, text: 'Arrange rice in bowls, smoothing it into an even layer.', durationMinutes: 3, assignedToHelper: 2 },
    { order: 3, text: 'Spread salmon cubes, cucumber and avocado neatly on top of the rice.', durationMinutes: 7, assignedToHelper: 3 },
    { order: 4, text: 'Drizzle soy sauce over the toppings or serve it on the side for dipping.', durationMinutes: 4, assignedToHelper: 4 },
    { order: 5, text: 'Sprinkle sesame seeds and enjoy immediately.', durationMinutes: 4, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 640,
    proteinGramsPerPortion: 30,
    fatGramsPerPortion: 24,
    carbsGramsPerPortion: 74,
    },
    },
    
    {
    id: 'seed-japanese-omurice-34',
    title: 'Japanese Omurice',
    description: 'Ketchup fried rice wrapped in a soft omelette.',
    diet: 'none',
    totalMinutes: 30,
    cuisine: 'japanese',
    likes: 58,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    { name: 'Chicken breast, small cubes', quantity: 120, unit: 'g', isFromUser: true },
    { name: 'Onion, finely chopped', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Frozen peas', quantity: 60, unit: 'g', isFromUser: true },
    { name: 'Eggs', quantity: 3, unit: 'pcs', isFromUser: true },
    { name: 'Ketchup', quantity: 3, unit: 'tbsp', isFromUser: false },
    { name: 'Oil or butter', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Fry chicken and onion in a little oil until the meat is cooked and onions soften.', durationMinutes: 8, assignedToHelper: 1 },
    { order: 2, text: 'Add rice and peas to the pan and stir-fry while breaking up rice clumps.', durationMinutes: 6, assignedToHelper: 2 },
    { order: 3, text: 'Squeeze ketchup over the rice and stir until all grains are evenly tinted.', durationMinutes: 4, assignedToHelper: 3 },
    { order: 4, text: 'In a clean pan cook beaten eggs into a soft thin omelette, keeping the center slightly runny.', durationMinutes: 6, assignedToHelper: 4 },
    { order: 5, text: 'Place fried rice on a plate and drape the omelette over, then decorate with extra ketchup.', durationMinutes: 6, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 720,
    proteinGramsPerPortion: 29,
    fatGramsPerPortion: 24,
    carbsGramsPerPortion: 92,
    },
    },
    
    {
    id: 'seed-japanese-miso-butter-corn-rice-35',
    title: 'Miso Butter Corn Rice',
    description: 'Rice tossed with miso butter, sweet corn and spring onions.',
    diet: 'vegetarian',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 31,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Cooked white rice', quantity: 260, unit: 'g', isFromUser: true },
    { name: 'Corn kernels, canned or frozen', quantity: 120, unit: 'g', isFromUser: true },
    { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Butter', quantity: 20, unit: 'g', isFromUser: true },
    { name: 'White miso paste', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Soy sauce', quantity: 1, unit: 'tsp', isFromUser: false },
    ],
    steps: [
    { order: 1, text: 'Melt butter in a small pan and stir in miso and soy sauce until combined.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Warm corn briefly in the miso butter so it absorbs some flavor.', durationMinutes: 4, assignedToHelper: 2 },
    { order: 3, text: 'Place hot rice in a bowl and pour the miso corn mixture over it.', durationMinutes: 4, assignedToHelper: 3 },
    { order: 4, text: 'Fold everything together gently so the rice grains stay separate.', durationMinutes: 5, assignedToHelper: 4 },
    { order: 5, text: 'Top with plenty of sliced spring onions and serve.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 520,
    proteinGramsPerPortion: 11,
    fatGramsPerPortion: 15,
    carbsGramsPerPortion: 86,
    },
    },
    
    {
    id: 'seed-japanese-chicken-eggplant-miso-36',
    title: 'Chicken and Eggplant Miso Stir-Fry',
    description: 'Stir-fried chicken and eggplant in a rich miso sauce.',
    diet: 'none',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 45,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Chicken thigh, strips', quantity: 220, unit: 'g', isFromUser: true },
    { name: 'Eggplant, half-moons', quantity: 250, unit: 'g', isFromUser: true },
    { name: 'Spring onions, sliced', quantity: 1, unit: 'pcs', isFromUser: true, isOptional: true },
    { name: 'White miso paste', quantity: 1.5, unit: 'tbsp', isFromUser: false },
    { name: 'Soy sauce', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Sugar', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Oil', quantity: 2, unit: 'tbsp', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Mix miso, soy sauce, sugar and a splash of water into a thick sauce.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Heat half the oil in a pan and brown the chicken strips until nearly cooked.', durationMinutes: 7, assignedToHelper: 2 },
    { order: 3, text: 'Remove the chicken, add remaining oil and fry eggplant until soft and lightly browned.', durationMinutes: 7, assignedToHelper: 3 },
    { order: 4, text: 'Return chicken to the pan, pour over the miso sauce and toss until everything is coated.', durationMinutes: 5, assignedToHelper: 4 },
    { order: 5, text: 'Serve the stir-fry hot with spring onions sprinkled on top.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 610,
    proteinGramsPerPortion: 28,
    fatGramsPerPortion: 32,
    carbsGramsPerPortion: 40,
    },
    },
    
    {
    id: 'seed-japanese-keto-salmon-avocado-bowl-37',
    title: 'Keto Salmon Avocado Bowl',
    description: 'Low-carb bowl with salmon, avocado and cabbage in soy dressing.',
    diet: 'keto',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 40,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Fresh salmon, slices', quantity: 180, unit: 'g', isFromUser: true },
    { name: 'Avocado, cubes', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'White cabbage, shredded', quantity: 120, unit: 'g', isFromUser: true },
    { name: 'Cucumber, thin slices', quantity: 0.5, unit: 'pcs', isFromUser: true },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Sesame oil', quantity: 1, unit: 'tsp', isFromUser: false },
    { name: 'Lemon juice', quantity: 1, unit: 'tbsp', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Toss shredded cabbage and cucumber with lemon juice in a bowl and set aside.', durationMinutes: 5, assignedToHelper: 1 },
    { order: 2, text: 'Arrange cabbage mixture in serving bowls as a light base.', durationMinutes: 3, assignedToHelper: 2 },
    { order: 3, text: 'Lay salmon slices and avocado cubes neatly over the vegetables.', durationMinutes: 5, assignedToHelper: 3 },
    { order: 4, text: 'Mix soy sauce and sesame oil and drizzle it over each bowl.', durationMinutes: 4, assignedToHelper: 4 },
    { order: 5, text: 'Serve immediately while the textures are still fresh.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 520,
    proteinGramsPerPortion: 28,
    fatGramsPerPortion: 36,
    carbsGramsPerPortion: 10,
    },
    },
    
    {
    id: 'seed-japanese-keto-beef-lettuce-cups-38',
    title: 'Keto Beef Lettuce Cups',
    description: 'Soy ginger beef served in crisp lettuce leaves.',
    diet: 'keto',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 29,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Ground beef', quantity: 250, unit: 'g', isFromUser: true },
    { name: 'Iceberg lettuce leaves', quantity: 8, unit: 'pcs', isFromUser: true },
    { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Fresh ginger, grated', quantity: 1, unit: 'tbsp', isFromUser: true },
    { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    { name: 'Sesame oil', quantity: 1, unit: 'tsp', isFromUser: false },
    { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Heat oil in a pan and cook ground beef while breaking it into small pieces.', durationMinutes: 6, assignedToHelper: 1 },
    { order: 2, text: 'Add grated ginger and cook briefly until fragrant.', durationMinutes: 3, assignedToHelper: 2 },
    { order: 3, text: 'Stir in soy sauce and sesame oil and let the beef absorb the flavors.', durationMinutes: 4, assignedToHelper: 3 },
    { order: 4, text: 'Arrange lettuce leaves on plates and spoon hot beef mixture into each.', durationMinutes: 4, assignedToHelper: 4 },
    { order: 5, text: 'Scatter spring onions over the cups and serve as hand-held bites.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 480,
    proteinGramsPerPortion: 29,
    fatGramsPerPortion: 35,
    carbsGramsPerPortion: 6,
    },
    },
    
    {
    id: 'seed-japanese-keto-miso-salmon-39',
    title: 'Keto Miso Salmon with Greens',
    description: 'Baked miso salmon served with sautéed greens.',
    diet: 'keto',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 46,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Salmon fillets', quantity: 2, unit: 'pcs', isFromUser: true },
    { name: 'Spinach or pak choi', quantity: 150, unit: 'g', isFromUser: true },
    { name: 'White miso paste', quantity: 1.5, unit: 'tbsp', isFromUser: false },
    { name: 'Soy sauce', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Sesame oil', quantity: 1, unit: 'tsp', isFromUser: false },
    { name: 'Oil or butter', quantity: 1, unit: 'tbsp', isFromUser: true },
    ],
    steps: [
    { order: 1, text: 'Mix miso, soy sauce and a little water to make a smooth paste for the salmon.', durationMinutes: 4, assignedToHelper: 1 },
    { order: 2, text: 'Spread the miso mixture over the salmon fillets and place them in a baking dish.', durationMinutes: 4, assignedToHelper: 2 },
    { order: 3, text: 'Bake the salmon until just cooked, with the surface lightly caramelized.', durationMinutes: 12, assignedToHelper: 3 },
    { order: 4, text: 'Quickly sauté spinach or pak choi in hot oil or butter until just wilted.', durationMinutes: 4, assignedToHelper: 4 },
    { order: 5, text: 'Serve salmon with the greens and drizzle with a little sesame oil.', durationMinutes: 1, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 520,
    proteinGramsPerPortion: 34,
    fatGramsPerPortion: 34,
    carbsGramsPerPortion: 6,
    },
    },
    
    {
    id: 'seed-japanese-keto-tofu-egg-bowl-40',
    title: 'Keto Tofu Egg Bowl',
    description: 'Soft scrambled eggs and tofu with soy butter over shredded cabbage.',
    diet: 'keto',
    totalMinutes: 15,
    cuisine: 'japanese',
    likes: 28,
    source: 'seed',
    createdAt: null,
    ingredients: [
    { name: 'Firm tofu, small cubes', quantity: 150, unit: 'g', isFromUser: true },
    { name: 'Eggs, beaten', quantity: 3, unit: 'pcs', isFromUser: true },
    { name: 'White cabbage, shredded', quantity: 120, unit: 'g', isFromUser: true },
    { name: 'Butter', quantity: 20, unit: 'g', isFromUser: true },
    { name: 'Soy sauce', quantity: 1, unit: 'tbsp', isFromUser: false },
    { name: 'Sesame seeds', quantity: 1, unit: 'tsp', isFromUser: true, isOptional: true },
    ],
    steps: [
    { order: 1, text: 'Place shredded cabbage in bowls to create a fresh crunchy base.', durationMinutes: 3, assignedToHelper: 1 },
    { order: 2, text: 'Melt butter in a pan and gently fry tofu cubes until warmed and lightly colored.', durationMinutes: 4, assignedToHelper: 2 },
    { order: 3, text: 'Pour beaten eggs over the tofu and stir slowly to make soft scrambled eggs.', durationMinutes: 5, assignedToHelper: 3 },
    { order: 4, text: 'Season the egg mixture with soy sauce near the end of cooking.', durationMinutes: 2, assignedToHelper: 4 },
    { order: 5, text: 'Spoon tofu and egg over the cabbage and sprinkle with sesame seeds.', durationMinutes: 1, assignedToHelper: 1 },
    ],
    nutrition: {
    energyKcalPerPortion: 430,
    proteinGramsPerPortion: 28,
    fatGramsPerPortion: 30,
    carbsGramsPerPortion: 7,
    },
    }
    
];

