export type Diet = 'vegetarian' | 'vegan' | 'keto' | 'none';
export type Cuisine = 'german' | 'italian' | 'indian' | 'japanese' | 'gourmet' | 'fusion';

export interface SeedIngredient {
  name: string;
  quantity: number;
  unit: string;
  isFromUser: boolean;
  isOptional?: boolean;
}

export interface SeedStep {
  order: number;
  text: string;
  durationMinutes?: number;
  parallelGroup?: string;
  assignedToHelper: 1 | 2 | 3 | 4; 
}

export interface SeedNutrition {
  energyKcalPerPortion: number;
  proteinGramsPerPortion: number;
  fatGramsPerPortion: number;
  carbsGramsPerPortion: number;
}

export interface FirestoreRecipe {
  id: string;
  title: string;
  description?: string;
  diet: Diet;
  totalMinutes: number;
  cuisine: Cuisine;
  ingredients: SeedIngredient[];
  steps: SeedStep[];
  nutrition?: SeedNutrition;
  likes: number;
  source: 'ai' | 'seed';
  createdAt: any;
}

export const SEED_RECIPES: FirestoreRecipe[] = [
   // ---------- JAPANESE (10 RECIPES) ----------

   {
    id: 'seed-japanese-chicken-teriyaki-1',
    title: 'Chicken Teriyaki with Rice',
    description: 'Juicy pan-fried chicken in a glossy teriyaki sauce, served with steamed rice.',
    diet: 'none',
    totalMinutes: 30,
    cuisine: 'japanese',
    likes: 51,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Chicken thighs, boneless', quantity: 300, unit: 'g', isFromUser: false },
      { name: 'Soy sauce', quantity: 3, unit: 'tbsp', isFromUser: false },
      { name: 'Mirin or sweet rice wine', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Sugar or honey', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Ginger, grated', quantity: 1, unit: 'tsp', isFromUser: false, isOptional: true },
      { name: 'Garlic, minced', quantity: 1, unit: 'clove', isFromUser: false, isOptional: true },
      { name: 'Cooked rice', quantity: 250, unit: 'g', isFromUser: false },
      { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: false, isOptional: true },
      { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Cook the rice according to package instructions and keep warm.', durationMinutes: 15, assignedToHelper: 1 },
      { order: 2, text: 'Mix soy sauce, mirin and sugar (plus ginger and garlic if using) to make the teriyaki sauce.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Heat oil in a pan and fry the chicken thighs on both sides until browned and almost cooked through.', durationMinutes: 8, assignedToHelper: 1 },
      { order: 4, text: 'Pour the teriyaki sauce over the chicken and simmer until the sauce thickens and coats the meat.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 5, text: 'Slice the chicken, serve over rice and sprinkle with sliced spring onions.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 650,
      proteinGramsPerPortion: 35,
      fatGramsPerPortion: 18,
      carbsGramsPerPortion: 80,
    },
  },

  {
    id: 'seed-japanese-vegan-donburi-1',
    title: 'Vegan Tofu Donburi Bowl',
    description: 'Rice bowl topped with marinated tofu, vegetables and a light soy-based sauce.',
    diet: 'vegan',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 39,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Firm tofu, cubed', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Cooked rice', quantity: 250, unit: 'g', isFromUser: false },
      { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Sesame oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Rice vinegar', quantity: 1, unit: 'tbsp', isFromUser: false, isOptional: true },
      { name: 'Carrot, julienned', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Cucumber, thinly sliced', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Edamame (shelled)', quantity: 80, unit: 'g', isFromUser: false, isOptional: true },
      { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Sesame seeds', quantity: 1, unit: 'tbsp', isFromUser: false, isOptional: true },
      { name: 'Oil for frying', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Cook the rice and keep it warm in serving bowls.', durationMinutes: 12, assignedToHelper: 1 },
      { order: 2, text: 'Pat the tofu dry, then pan-fry the cubes in a little oil until golden on all sides.', durationMinutes: 8, assignedToHelper: 2 },
      { order: 3, text: 'Mix soy sauce, sesame oil and rice vinegar (if using) to make a quick dressing.', durationMinutes: 3, assignedToHelper: 1 },
      { order: 4, text: 'Arrange tofu, carrot, cucumber and edamame on top of the rice, drizzle with the dressing.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 5, text: 'Garnish with spring onions and sesame seeds and serve immediately.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 580,
      proteinGramsPerPortion: 22,
      fatGramsPerPortion: 18,
      carbsGramsPerPortion: 80,
    },
  },

  {
    id: 'seed-japanese-keto-salmon-1',
    title: 'Keto Miso-Glazed Salmon with Greens',
    description: 'Oven-baked salmon fillet with miso glaze, served with low-carb stir-fried greens.',
    diet: 'keto',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 46,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Salmon fillets', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'White miso paste', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Soy sauce', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Lemon juice', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Broccoli florets', quantity: 150, unit: 'g', isFromUser: false },
      { name: 'Pak choi or spinach', quantity: 100, unit: 'g', isFromUser: false },
      { name: 'Sesame oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Sesame seeds', quantity: 1, unit: 'tbsp', isFromUser: false, isOptional: true },
    ],
    steps: [
      { order: 1, text: 'Preheat the oven to 190°C (375°F).', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Mix miso paste, soy sauce and lemon juice to form a glaze and spread it over the salmon fillets.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Bake the salmon on a lined tray for 12–15 minutes until just cooked through.', durationMinutes: 15, assignedToHelper: 1 },
      { order: 4, text: 'Meanwhile, stir-fry broccoli and pak choi in oil and sesame oil until crisp-tender.', durationMinutes: 8, assignedToHelper: 2 },
      { order: 5, text: 'Serve the salmon on top of the greens and sprinkle with sesame seeds.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 520,
      proteinGramsPerPortion: 35,
      fatGramsPerPortion: 34,
      carbsGramsPerPortion: 8,
    },
  },

  {
    id: 'seed-japanese-udon-soup-1',
    title: 'Quick Udon Noodle Soup',
    description: 'Comforting bowl of udon noodles in a light broth with vegetables.',
    diet: 'none',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 40,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Udon noodles (fresh or cooked)', quantity: 300, unit: 'g', isFromUser: false },
      { name: 'Vegetable or dashi stock', quantity: 800, unit: 'ml', isFromUser: false },
      { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Mushrooms, sliced', quantity: 100, unit: 'g', isFromUser: false },
      { name: 'Carrot, julienned', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Baby spinach or pak choi', quantity: 50, unit: 'g', isFromUser: false },
      { name: 'Soft-boiled egg', quantity: 2, unit: 'pcs', isFromUser: false, isOptional: true },
    ],
    steps: [
      { order: 1, text: 'Heat the stock in a pot, add soy sauce and bring to a gentle simmer.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Add sliced mushrooms and carrot to the broth and cook until just tender.', durationMinutes: 6, assignedToHelper: 2 },
      { order: 3, text: 'Add the udon noodles and spinach or pak choi and heat through.', durationMinutes: 4, assignedToHelper: 1 },
      { order: 4, text: 'Divide the soup between bowls, top with spring onions and halved soft-boiled eggs if using.', durationMinutes: 5, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 480,
      proteinGramsPerPortion: 18,
      fatGramsPerPortion: 10,
      carbsGramsPerPortion: 80,
    },
  },

  {
    id: 'seed-japanese-omurice-1',
    title: 'Japanese Omurice',
    description: 'Fried rice wrapped in a soft omelette, topped with ketchup.',
    diet: 'none',
    totalMinutes: 25,
    cuisine: 'japanese',
    likes: 42,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Cooked rice', quantity: 250, unit: 'g', isFromUser: false },
      { name: 'Eggs', quantity: 3, unit: 'pcs', isFromUser: false },
      { name: 'Onion, finely chopped', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Carrot, finely diced', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Frozen peas', quantity: 40, unit: 'g', isFromUser: false, isOptional: true },
      { name: 'Ketchup', quantity: 3, unit: 'tbsp', isFromUser: false },
      { name: 'Oil or butter', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.25, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Sauté onion and carrot in a pan with a little oil until softened.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Add the cooked rice and peas, fry briefly and season with salt, pepper and ketchup.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'In a clean pan, whisk eggs with a pinch of salt, then cook a soft, slightly runny omelette.', durationMinutes: 7, assignedToHelper: 1 },
      { order: 4, text: 'Place the fried rice in the center of the omelette and fold the sides over.', durationMinutes: 4, assignedToHelper: 2 },
      { order: 5, text: 'Slide onto a plate and drizzle with extra ketchup.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 550,
      proteinGramsPerPortion: 22,
      fatGramsPerPortion: 20,
      carbsGramsPerPortion: 70,
    },
  },

  {
    id: 'seed-japanese-vegan-miso-soup-1',
    title: 'Vegan Miso Soup with Tofu',
    description: 'Light miso broth with tofu cubes and wakame seaweed.',
    diet: 'vegan',
    totalMinutes: 15,
    cuisine: 'japanese',
    likes: 35,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Vegetable or kombu-based stock', quantity: 600, unit: 'ml', isFromUser: false },
      { name: 'White miso paste', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Firm tofu, cubed', quantity: 100, unit: 'g', isFromUser: false },
      { name: 'Dried wakame, soaked', quantity: 5, unit: 'g', isFromUser: false },
      { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Heat the vegetable or kombu stock until hot but not boiling.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Ladle some hot stock into a small bowl and dissolve the miso paste in it.', durationMinutes: 3, assignedToHelper: 2 },
      { order: 3, text: 'Add tofu cubes and soaked wakame to the pot.', durationMinutes: 3, assignedToHelper: 1 },
      { order: 4, text: 'Stir the dissolved miso back into the pot and gently warm without boiling.', durationMinutes: 3, assignedToHelper: 2 },
      { order: 5, text: 'Serve in bowls and garnish with sliced spring onions.', durationMinutes: 1, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 150,
      proteinGramsPerPortion: 9,
      fatGramsPerPortion: 6,
      carbsGramsPerPortion: 14,
    },
  },

  {
    id: 'seed-japanese-katsu-curry-1',
    title: 'Chicken Katsu Curry',
    description: 'Crispy breaded chicken cutlet served with Japanese-style curry sauce and rice.',
    diet: 'none',
    totalMinutes: 40,
    cuisine: 'japanese',
    likes: 60,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Chicken breast', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Flour', quantity: 40, unit: 'g', isFromUser: false },
      { name: 'Egg', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Panko breadcrumbs', quantity: 80, unit: 'g', isFromUser: false },
      { name: 'Onion, sliced', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Carrot, sliced', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Potato, cubed', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Japanese curry roux or powder', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Water or stock', quantity: 600, unit: 'ml', isFromUser: false },
      { name: 'Cooked rice', quantity: 250, unit: 'g', isFromUser: false },
      { name: 'Oil for frying', quantity: 3, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Sauté onion, carrot and potato in a pot, then add water or stock and simmer until tender.', durationMinutes: 20, assignedToHelper: 1 },
      { order: 2, text: 'Stir in the Japanese curry roux or powder and cook until the sauce thickens.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Flatten the chicken, season lightly, then coat in flour, beaten egg and panko.', durationMinutes: 7, assignedToHelper: 1 },
      { order: 4, text: 'Fry the breaded chicken in hot oil until golden and cooked through.', durationMinutes: 8, assignedToHelper: 2 },
      { order: 5, text: 'Slice the chicken and serve over rice with the curry sauce.', durationMinutes: 5, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 800,
      proteinGramsPerPortion: 35,
      fatGramsPerPortion: 35,
      carbsGramsPerPortion: 90,
    },
  },

  {
    id: 'seed-japanese-keto-egg-roll-1',
    title: 'Keto Tamagoyaki Egg Roll',
    description: 'Rolled Japanese omelette with a light soy-dashi seasoning.',
    diet: 'keto',
    totalMinutes: 15,
    cuisine: 'japanese',
    likes: 32,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Eggs', quantity: 3, unit: 'pcs', isFromUser: false },
      { name: 'Soy sauce', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Water or dashi', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Sugar or sweetener', quantity: 0.5, unit: 'tsp', isFromUser: false, isOptional: true },
      { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Whisk eggs with soy sauce, water or dashi and sugar or sweetener if using.', durationMinutes: 3, assignedToHelper: 1 },
      { order: 2, text: 'Heat a small non-stick pan with oil and pour in a thin layer of egg mixture.', durationMinutes: 3, assignedToHelper: 2 },
      { order: 3, text: 'When almost set, roll the egg to one side, then add more egg mixture and repeat the rolling.', durationMinutes: 6, assignedToHelper: 1 },
      { order: 4, text: 'Let the egg roll cool slightly, then slice into thick pieces and serve.', durationMinutes: 3, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 220,
      proteinGramsPerPortion: 15,
      fatGramsPerPortion: 17,
      carbsGramsPerPortion: 2,
    },
  },

  {
    id: 'seed-japanese-cold-soba-1',
    title: 'Cold Soba Noodles with Dipping Sauce',
    description: 'Buckwheat soba noodles served chilled with a soy-based dipping sauce.',
    diet: 'vegan',
    totalMinutes: 20,
    cuisine: 'japanese',
    likes: 34,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Soba noodles', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Soy sauce', quantity: 3, unit: 'tbsp', isFromUser: false },
      { name: 'Water', quantity: 150, unit: 'ml', isFromUser: false },
      { name: 'Mirin or sugar', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Nori strips', quantity: 1, unit: 'tbsp', isFromUser: false, isOptional: true },
      { name: 'Wasabi', quantity: 0.5, unit: 'tsp', isFromUser: false, isOptional: true },
    ],
    steps: [
      { order: 1, text: 'Cook soba noodles according to package instructions, then rinse under cold water and drain well.', durationMinutes: 10, assignedToHelper: 1 },
      { order: 2, text: 'Mix soy sauce, water and mirin or sugar to create a dipping sauce.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Arrange the cold soba on a plate and top with nori strips if using.', durationMinutes: 3, assignedToHelper: 1 },
      { order: 4, text: 'Serve with dipping sauce, spring onions and wasabi on the side.', durationMinutes: 2, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 380,
      proteinGramsPerPortion: 14,
      fatGramsPerPortion: 3,
      carbsGramsPerPortion: 75,
    },
  },

  // ---------- INDIAN (10 RECIPES) ----------

  {
    id: 'seed-indian-chicken-curry-1',
    title: 'Simple Chicken Curry',
    description: 'Mild Indian-style chicken curry with tomatoes and yogurt.',
    diet: 'none',
    totalMinutes: 35,
    cuisine: 'indian',
    likes: 55,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Chicken breast, cubed', quantity: 300, unit: 'g', isFromUser: false },
      { name: 'Onion, finely chopped', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Garlic cloves, minced', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Ginger, grated', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Tomato passata', quantity: 200, unit: 'ml', isFromUser: false },
      { name: 'Plain yogurt', quantity: 80, unit: 'g', isFromUser: false },
      { name: 'Curry powder or garam masala', quantity: 2, unit: 'tsp', isFromUser: false },
      { name: 'Oil', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Sauté onion in oil until golden.', durationMinutes: 8, assignedToHelper: 1 },
      { order: 2, text: 'Add garlic and ginger and fry briefly.', durationMinutes: 3, assignedToHelper: 2 },
      { order: 3, text: 'Stir in curry powder or garam masala, then add chicken pieces and brown on all sides.', durationMinutes: 8, assignedToHelper: 1 },
      { order: 4, text: 'Add tomato passata and simmer until the chicken is cooked through.', durationMinutes: 10, assignedToHelper: 2 },
      { order: 5, text: 'Stir in yogurt off the heat, season with salt and serve.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 520,
      proteinGramsPerPortion: 35,
      fatGramsPerPortion: 28,
      carbsGramsPerPortion: 20,
    },
  },

  {
    id: 'seed-indian-chana-masala-1',
    title: 'Chana Masala (Chickpea Curry)',
    description: 'Spiced tomato-based chickpea curry, naturally vegan.',
    diet: 'vegan',
    totalMinutes: 30,
    cuisine: 'indian',
    likes: 48,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Cooked or canned chickpeas, drained', quantity: 250, unit: 'g', isFromUser: false },
      { name: 'Onion, chopped', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Garlic cloves, minced', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Ginger, grated', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Tomato passata', quantity: 200, unit: 'ml', isFromUser: false },
      { name: 'Chana masala spice mix or garam masala', quantity: 2, unit: 'tsp', isFromUser: false },
      { name: 'Oil', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Sauté onion in oil until soft.', durationMinutes: 6, assignedToHelper: 1 },
      { order: 2, text: 'Add garlic and ginger and cook briefly.', durationMinutes: 3, assignedToHelper: 2 },
      { order: 3, text: 'Stir in spice mix and toast for 1 minute.', durationMinutes: 1, assignedToHelper: 1 },
      { order: 4, text: 'Add tomato passata and simmer for a few minutes.', durationMinutes: 7, assignedToHelper: 2 },
      { order: 5, text: 'Add chickpeas, simmer until heated through, season with salt and serve.', durationMinutes: 8, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 430,
      proteinGramsPerPortion: 18,
      fatGramsPerPortion: 14,
      carbsGramsPerPortion: 55,
    },
  },

  {
    id: 'seed-indian-keto-butter-chicken-1',
    title: 'Keto Butter Chicken',
    description: 'Creamy butter chicken with a rich tomato sauce, served without rice for low carbs.',
    diet: 'keto',
    totalMinutes: 40,
    cuisine: 'indian',
    likes: 59,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Chicken thighs, cubed', quantity: 300, unit: 'g', isFromUser: false },
      { name: 'Butter', quantity: 40, unit: 'g', isFromUser: false },
      { name: 'Cream', quantity: 100, unit: 'ml', isFromUser: false },
      { name: 'Tomato passata', quantity: 200, unit: 'ml', isFromUser: false },
      { name: 'Onion, chopped', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Garlic and ginger paste', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Garam masala', quantity: 2, unit: 'tsp', isFromUser: false },
      { name: 'Chili powder', quantity: 0.5, unit: 'tsp', isFromUser: false, isOptional: true },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Sauté onion in half the butter until golden.', durationMinutes: 8, assignedToHelper: 1 },
      { order: 2, text: 'Add garlic-ginger paste and garam masala, cook briefly.', durationMinutes: 3, assignedToHelper: 2 },
      { order: 3, text: 'Add chicken pieces and brown on all sides.', durationMinutes: 8, assignedToHelper: 1 },
      { order: 4, text: 'Stir in tomato passata, simmer until chicken is tender.', durationMinutes: 15, assignedToHelper: 2 },
      { order: 5, text: 'Stir in cream and remaining butter, season and serve without rice or with cauliflower rice.', durationMinutes: 6, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 650,
      proteinGramsPerPortion: 38,
      fatGramsPerPortion: 48,
      carbsGramsPerPortion: 10,
    },
  },

  {
    id: 'seed-indian-saag-paneer-1',
    title: 'Saag Paneer',
    description: 'Creamy spinach curry with fried paneer cubes.',
    diet: 'vegetarian',
    totalMinutes: 35,
    cuisine: 'indian',
    likes: 44,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Paneer, cubed', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Spinach, fresh or frozen', quantity: 300, unit: 'g', isFromUser: false },
      { name: 'Onion, chopped', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Garlic cloves, minced', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Ginger, grated', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Cream or yogurt', quantity: 80, unit: 'ml', isFromUser: false },
      { name: 'Garam masala', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Oil or ghee', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Fry paneer cubes in a pan with a little oil until golden, then set aside.', durationMinutes: 8, assignedToHelper: 1 },
      { order: 2, text: 'Sauté onion, garlic and ginger in oil until soft.', durationMinutes: 7, assignedToHelper: 2 },
      { order: 3, text: 'Add spinach and cook until wilted (or thawed).', durationMinutes: 5, assignedToHelper: 1 },
      { order: 4, text: 'Blend the spinach mixture to a coarse puree if desired, then return to the pan.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 5, text: 'Stir in cream or yogurt, garam masala and fried paneer, simmer briefly and season with salt.', durationMinutes: 10, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 520,
      proteinGramsPerPortion: 24,
      fatGramsPerPortion: 36,
      carbsGramsPerPortion: 18,
    },
  },

  {
    id: 'seed-indian-veggie-biryani-1',
    title: 'Vegetable Biryani',
    description: 'Fragrant basmati rice with mixed vegetables and warm spices.',
    diet: 'vegetarian',
    totalMinutes: 45,
    cuisine: 'indian',
    likes: 52,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Basmati rice', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Mixed vegetables (carrot, peas, beans)', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Onion, thinly sliced', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Yogurt', quantity: 60, unit: 'g', isFromUser: false },
      { name: 'Biryani masala or garam masala', quantity: 2, unit: 'tsp', isFromUser: false },
      { name: 'Oil or ghee', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Parboil basmati rice in salted water until almost cooked, then drain.', durationMinutes: 12, assignedToHelper: 1 },
      { order: 2, text: 'Fry sliced onion in oil or ghee until golden.', durationMinutes: 8, assignedToHelper: 2 },
      { order: 3, text: 'Add vegetables, yogurt and spices, cook briefly.', durationMinutes: 7, assignedToHelper: 1 },
      { order: 4, text: 'Layer rice and vegetable mixture in a pot, cover and steam on low heat.', durationMinutes: 15, assignedToHelper: 2 },
      { order: 5, text: 'Fluff gently with a fork and serve.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 560,
      proteinGramsPerPortion: 15,
      fatGramsPerPortion: 18,
      carbsGramsPerPortion: 85,
    },
  },

  {
    id: 'seed-indian-dal-tadka-1',
    title: 'Dal Tadka (Lentil Curry)',
    description: 'Yellow lentils cooked soft and finished with a spiced tempering.',
    diet: 'vegan',
    totalMinutes: 35,
    cuisine: 'indian',
    likes: 45,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Yellow lentils (toor or moong dal)', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Water', quantity: 700, unit: 'ml', isFromUser: false },
      { name: 'Onion, chopped', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Tomato, chopped', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Garlic cloves, sliced', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Turmeric powder', quantity: 0.5, unit: 'tsp', isFromUser: false },
      { name: 'Chili powder', quantity: 0.5, unit: 'tsp', isFromUser: false, isOptional: true },
      { name: 'Oil or ghee', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Rinse lentils and cook with water and turmeric until very soft.', durationMinutes: 20, assignedToHelper: 1 },
      { order: 2, text: 'Mash the cooked lentils lightly and add chopped tomato and salt, simmer briefly.', durationMinutes: 7, assignedToHelper: 2 },
      { order: 3, text: 'In a small pan, heat oil or ghee, add cumin seeds and sliced garlic.', durationMinutes: 3, assignedToHelper: 1 },
      { order: 4, text: 'When fragrant and lightly browned, add chili powder if using and pour the tempering over the dal.', durationMinutes: 3, assignedToHelper: 2 },
      { order: 5, text: 'Stir and serve hot with rice or flatbread.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 380,
      proteinGramsPerPortion: 18,
      fatGramsPerPortion: 10,
      carbsGramsPerPortion: 52,
    },
  },

  {
    id: 'seed-indian-keto-cauliflower-rice-1',
    title: 'Keto Cauliflower Rice with Spices',
    description: 'Grated cauliflower sautéed with Indian spices as a low-carb side.',
    diet: 'keto',
    totalMinutes: 15,
    cuisine: 'indian',
    likes: 33,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Cauliflower, grated', quantity: 250, unit: 'g', isFromUser: false },
      { name: 'Onion, finely chopped', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Cumin seeds', quantity: 0.5, unit: 'tsp', isFromUser: false },
      { name: 'Turmeric powder', quantity: 0.25, unit: 'tsp', isFromUser: false },
      { name: 'Oil or ghee', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Heat oil or ghee in a pan, add cumin seeds until they sizzle.', durationMinutes: 2, assignedToHelper: 1 },
      { order: 2, text: 'Add chopped onion and cook until translucent.', durationMinutes: 4, assignedToHelper: 2 },
      { order: 3, text: 'Stir in grated cauliflower and turmeric.', durationMinutes: 3, assignedToHelper: 1 },
      { order: 4, text: 'Cook, stirring, until the cauliflower is tender but not mushy, then season with salt.', durationMinutes: 6, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 140,
      proteinGramsPerPortion: 5,
      fatGramsPerPortion: 9,
      carbsGramsPerPortion: 10,
    },
  },

  {
    id: 'seed-indian-paneer-tikka-1',
    title: 'Oven Paneer Tikka',
    description: 'Marinated paneer cubes baked until lightly charred.',
    diet: 'vegetarian',
    totalMinutes: 30,
    cuisine: 'indian',
    likes: 47,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Paneer, cubed', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Yogurt', quantity: 80, unit: 'g', isFromUser: false },
      { name: 'Tikka masala spice mix', quantity: 2, unit: 'tsp', isFromUser: false },
      { name: 'Lemon juice', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Preheat the oven grill to high.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Mix yogurt, spice mix, lemon juice, oil and salt to form a marinade.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Coat paneer cubes in the marinade and let sit briefly.', durationMinutes: 10, assignedToHelper: 1 },
      { order: 4, text: 'Place paneer on a lined baking tray and grill until edges are slightly charred.', durationMinutes: 8, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 420,
      proteinGramsPerPortion: 22,
      fatGramsPerPortion: 30,
      carbsGramsPerPortion: 8,
    },
  },

  {
    id: 'seed-indian-masala-omelette-1',
    title: 'Masala Omelette',
    description: 'Indian-style omelette with onions, tomatoes and fresh herbs.',
    diet: 'none',
    totalMinutes: 15,
    cuisine: 'indian',
    likes: 36,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Eggs', quantity: 3, unit: 'pcs', isFromUser: false },
      { name: 'Onion, finely chopped', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Tomato, finely chopped', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Fresh coriander, chopped', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Green chili, finely chopped', quantity: 0.5, unit: 'pcs', isFromUser: false, isOptional: true },
      { name: 'Oil or ghee', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Beat eggs with salt in a bowl.', durationMinutes: 2, assignedToHelper: 1 },
      { order: 2, text: 'Stir in chopped onion, tomato, coriander and chili if using.', durationMinutes: 3, assignedToHelper: 2 },
      { order: 3, text: 'Heat oil in a pan and pour in the egg mixture.', durationMinutes: 2, assignedToHelper: 1 },
      { order: 4, text: 'Cook until the omelette is set and lightly browned, then fold and serve.', durationMinutes: 8, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 280,
      proteinGramsPerPortion: 18,
      fatGramsPerPortion: 22,
      carbsGramsPerPortion: 4,
    },
  },

  // ---------- GOURMET (10 RECIPES) ----------

  {
    id: 'seed-gourmet-beef-wellington-1',
    title: 'Mini Beef Wellington',
    description: 'Individual beef fillets wrapped in mushroom duxelles and puff pastry.',
    diet: 'none',
    totalMinutes: 70,
    cuisine: 'gourmet',
    likes: 66,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Beef fillet steaks', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Mushrooms, finely chopped', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Onion or shallot, finely chopped', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Puff pastry sheet', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Butter', quantity: 30, unit: 'g', isFromUser: false },
      { name: 'Egg yolk', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Mustard', quantity: 1, unit: 'tbsp', isFromUser: false, isOptional: true },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Season beef fillets with salt and pepper and sear briefly on all sides, then let cool.', durationMinutes: 10, assignedToHelper: 1 },
      { order: 2, text: 'Sauté chopped mushrooms and shallot in butter until dry and concentrated (duxelles).', durationMinutes: 15, assignedToHelper: 2 },
      { order: 3, text: 'Roll out puff pastry and, if desired, brush the beef with mustard.', durationMinutes: 8, assignedToHelper: 1 },
      { order: 4, text: 'Spread duxelles on the pastry, place beef on top, wrap and seal into small parcels.', durationMinutes: 10, assignedToHelper: 2 },
      { order: 5, text: 'Brush with egg yolk and bake at 200°C (390°F) until golden and the beef is medium.', durationMinutes: 25, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 780,
      proteinGramsPerPortion: 40,
      fatGramsPerPortion: 50,
      carbsGramsPerPortion: 40,
    },
  },

  {
    id: 'seed-gourmet-scallops-risotto-1',
    title: 'Seared Scallops on Lemon Risotto',
    description: 'Creamy risotto finished with lemon and Parmesan, topped with seared scallops.',
    diet: 'none',
    totalMinutes: 45,
    cuisine: 'gourmet',
    likes: 61,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Scallops', quantity: 8, unit: 'pcs', isFromUser: false },
      { name: 'Arborio rice', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Vegetable stock', quantity: 800, unit: 'ml', isFromUser: false },
      { name: 'Onion or shallot, finely chopped', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'White wine', quantity: 80, unit: 'ml', isFromUser: false, isOptional: true },
      { name: 'Parmesan, grated', quantity: 40, unit: 'g', isFromUser: false },
      { name: 'Butter', quantity: 40, unit: 'g', isFromUser: false },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Lemon zest', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Heat stock in a pot and keep warm.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Sauté chopped onion in butter, add rice and toast briefly.', durationMinutes: 7, assignedToHelper: 2 },
      { order: 3, text: 'Deglaze with white wine if using, then add stock ladle by ladle, stirring until rice is creamy.', durationMinutes: 20, assignedToHelper: 1 },
      { order: 4, text: 'Finish risotto with Parmesan, lemon zest, salt and pepper.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 5, text: 'Sear scallops in olive oil and butter over high heat until just browned on both sides, then serve on top of the risotto.', durationMinutes: 8, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 620,
      proteinGramsPerPortion: 30,
      fatGramsPerPortion: 22,
      carbsGramsPerPortion: 70,
    },
  },

  {
    id: 'seed-gourmet-vegan-beet-tartar-1',
    title: 'Vegan Beetroot Tartare',
    description: 'Finely diced roasted beetroot with capers and herbs, served as an elegant starter.',
    diet: 'vegan',
    totalMinutes: 35,
    cuisine: 'gourmet',
    likes: 37,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Cooked or roasted beetroot, finely diced', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Capers, chopped', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Shallot, finely chopped', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Gherkins, finely chopped', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Lemon juice', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Fresh herbs (parsley, chives)', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.25, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Finely dice beetroot and place in a bowl.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Add chopped capers, shallot, gherkins and herbs.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Mix with olive oil, lemon juice, salt and pepper.', durationMinutes: 3, assignedToHelper: 1 },
      { order: 4, text: 'Press into small ring molds on plates and carefully lift off to create tartare shapes.', durationMinutes: 10, assignedToHelper: 2 },
      { order: 5, text: 'Serve chilled as an appetizer.', durationMinutes: 5, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 160,
      proteinGramsPerPortion: 3,
      fatGramsPerPortion: 8,
      carbsGramsPerPortion: 19,
    },
  },

  {
    id: 'seed-gourmet-keto-duck-breast-1',
    title: 'Keto Duck Breast with Red Cabbage',
    description: 'Crispy duck breast with butter-sautéed red cabbage, low in carbs.',
    diet: 'keto',
    totalMinutes: 45,
    cuisine: 'gourmet',
    likes: 49,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Duck breasts', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Red cabbage, finely sliced', quantity: 250, unit: 'g', isFromUser: false },
      { name: 'Butter', quantity: 30, unit: 'g', isFromUser: false },
      { name: 'Red wine vinegar', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Score the duck skin, season with salt and pepper.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Place duck breasts skin-side down in a cold pan, then slowly render fat and crisp the skin.', durationMinutes: 15, assignedToHelper: 2 },
      { order: 3, text: 'Flip and cook until the duck is medium, then rest.', durationMinutes: 8, assignedToHelper: 1 },
      { order: 4, text: 'Sauté red cabbage in butter, season with salt and a splash of red wine vinegar.', durationMinutes: 12, assignedToHelper: 2 },
      { order: 5, text: 'Slice duck and serve on the cabbage.', durationMinutes: 5, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 620,
      proteinGramsPerPortion: 38,
      fatGramsPerPortion: 46,
      carbsGramsPerPortion: 10,
    },
  },

  {
    id: 'seed-gourmet-asparagus-poached-egg-1',
    title: 'Green Asparagus with Poached Egg',
    description: 'Light gourmet starter with blanched asparagus, poached egg and Parmesan.',
    diet: 'vegetarian',
    totalMinutes: 25,
    cuisine: 'gourmet',
    likes: 41,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Green asparagus spears', quantity: 300, unit: 'g', isFromUser: false },
      { name: 'Eggs', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Parmesan, shaved', quantity: 20, unit: 'g', isFromUser: false },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Lemon juice', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.25, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Trim asparagus and blanch in salted boiling water until just tender, then cool slightly.', durationMinutes: 8, assignedToHelper: 1 },
      { order: 2, text: 'Poach eggs in gently simmering water.', durationMinutes: 8, assignedToHelper: 2 },
      { order: 3, text: 'Arrange asparagus on plates and drizzle with olive oil and lemon juice.', durationMinutes: 3, assignedToHelper: 1 },
      { order: 4, text: 'Place poached eggs on top and sprinkle with Parmesan, salt and pepper.', durationMinutes: 4, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 260,
      proteinGramsPerPortion: 18,
      fatGramsPerPortion: 18,
      carbsGramsPerPortion: 6,
    },
  },

  {
    id: 'seed-gourmet-vegan-cauliflower-steak-1',
    title: 'Roasted Cauliflower Steak with Herb Oil',
    description: 'Thick cauliflower slices roasted and served with herb-infused oil.',
    diet: 'vegan',
    totalMinutes: 35,
    cuisine: 'gourmet',
    likes: 39,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Cauliflower, cut into thick slices', quantity: 300, unit: 'g', isFromUser: false },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Garlic clove, minced', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Fresh herbs (parsley, thyme)', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.25, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Preheat oven to 200°C (390°F).', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Brush cauliflower slices with olive oil, season with salt and pepper.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Roast on a tray until golden and tender.', durationMinutes: 20, assignedToHelper: 1 },
      { order: 4, text: 'Mix remaining olive oil with garlic and herbs and drizzle over the roasted cauliflower.', durationMinutes: 5, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 200,
      proteinGramsPerPortion: 6,
      fatGramsPerPortion: 14,
      carbsGramsPerPortion: 12,
    },
  },

  {
    id: 'seed-gourmet-keto-tuna-tartare-1',
    title: 'Keto Tuna Tartare',
    description: 'Raw tuna cubes with avocado and citrus dressing.',
    diet: 'keto',
    totalMinutes: 20,
    cuisine: 'gourmet',
    likes: 42,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Sushi-grade tuna, cubed', quantity: 150, unit: 'g', isFromUser: false },
      { name: 'Avocado, diced', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Lime juice', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Soy sauce', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Sesame oil', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Spring onion, finely sliced', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Salt', quantity: 0.25, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.25, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Combine tuna cubes and avocado in a bowl.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Mix lime juice, soy sauce and sesame oil to make a dressing.', durationMinutes: 3, assignedToHelper: 2 },
      { order: 3, text: 'Pour dressing over tuna and avocado, add spring onion, salt and pepper.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 4, text: 'Serve immediately, optionally shaped with a ring mold.', durationMinutes: 5, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 320,
      proteinGramsPerPortion: 25,
      fatGramsPerPortion: 22,
      carbsGramsPerPortion: 4,
    },
  },

  {
    id: 'seed-gourmet-mushroom-veloute-1',
    title: 'Mushroom Velouté Soup',
    description: 'Silky mushroom soup finished with cream and truffle oil.',
    diet: 'vegetarian',
    totalMinutes: 40,
    cuisine: 'gourmet',
    likes: 43,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Mushrooms, sliced', quantity: 300, unit: 'g', isFromUser: false },
      { name: 'Onion, chopped', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Butter', quantity: 30, unit: 'g', isFromUser: false },
      { name: 'Vegetable stock', quantity: 700, unit: 'ml', isFromUser: false },
      { name: 'Cream', quantity: 80, unit: 'ml', isFromUser: false },
      { name: 'Truffle oil', quantity: 0.5, unit: 'tsp', isFromUser: false, isOptional: true },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Sauté onion and mushrooms in butter until soft and lightly browned.', durationMinutes: 10, assignedToHelper: 1 },
      { order: 2, text: 'Add vegetable stock and simmer for 15–20 minutes.', durationMinutes: 20, assignedToHelper: 2 },
      { order: 3, text: 'Blend the soup until very smooth, then return to the pot.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 4, text: 'Stir in cream, season and finish with a few drops of truffle oil if using.', durationMinutes: 5, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 320,
      proteinGramsPerPortion: 9,
      fatGramsPerPortion: 25,
      carbsGramsPerPortion: 14,
    },
  },

  {
    id: 'seed-gourmet-vegan-lentil-salad-1',
    title: 'Warm Lentil Salad with Roasted Vegetables',
    description: 'Beluga lentils with roasted root vegetables and balsamic dressing.',
    diet: 'vegan',
    totalMinutes: 40,
    cuisine: 'gourmet',
    likes: 38,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Beluga or green lentils', quantity: 180, unit: 'g', isFromUser: false },
      { name: 'Carrots, cubed', quantity: 100, unit: 'g', isFromUser: false },
      { name: 'Parsnip or celeriac, cubed', quantity: 100, unit: 'g', isFromUser: false },
      { name: 'Red onion, wedges', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Balsamic vinegar', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Fresh herbs', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Cook lentils in salted water until just tender, then drain.', durationMinutes: 20, assignedToHelper: 1 },
      { order: 2, text: 'Toss root vegetables and onion with olive oil, salt and pepper and roast at 200°C until golden.', durationMinutes: 20, assignedToHelper: 2 },
      { order: 3, text: 'Combine warm lentils and roasted vegetables in a bowl.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 4, text: 'Dress with balsamic vinegar, extra olive oil and herbs, adjust seasoning.', durationMinutes: 5, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 420,
      proteinGramsPerPortion: 18,
      fatGramsPerPortion: 14,
      carbsGramsPerPortion: 55,
    },
  },

  // ---------- FUSION (10 RECIPES) ----------

  {
    id: 'seed-fusion-kimchi-pasta-1',
    title: 'Kimchi Cream Pasta',
    description: 'Spaghetti in a spicy kimchi cream sauce with a fusion twist.',
    diet: 'none',
    totalMinutes: 25,
    cuisine: 'fusion',
    likes: 52,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Spaghetti', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Kimchi, chopped', quantity: 80, unit: 'g', isFromUser: false },
      { name: 'Cream', quantity: 150, unit: 'ml', isFromUser: false },
      { name: 'Garlic clove, minced', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Butter or oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: false, isOptional: true },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Cook spaghetti in salted water until al dente.', durationMinutes: 10, assignedToHelper: 1 },
      { order: 2, text: 'Sauté garlic and chopped kimchi in butter or oil.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Add cream and simmer briefly to thicken, season lightly with salt.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 4, text: 'Toss drained pasta with the sauce and top with spring onions.', durationMinutes: 5, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 620,
      proteinGramsPerPortion: 17,
      fatGramsPerPortion: 26,
      carbsGramsPerPortion: 78,
    },
  },

  {
    id: 'seed-fusion-taco-rice-bowl-1',
    title: 'Taco Rice Bowl',
    description: 'Japanese-inspired taco rice with seasoned minced meat and salad toppings.',
    diet: 'none',
    totalMinutes: 30,
    cuisine: 'fusion',
    likes: 49,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Cooked rice', quantity: 250, unit: 'g', isFromUser: false },
      { name: 'Ground beef', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Onion, chopped', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Taco seasoning', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Lettuce, shredded', quantity: 50, unit: 'g', isFromUser: false },
      { name: 'Tomato, diced', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Cheese, grated', quantity: 30, unit: 'g', isFromUser: false, isOptional: true },
      { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Sauté onion and ground beef in oil until browned.', durationMinutes: 8, assignedToHelper: 1 },
      { order: 2, text: 'Add taco seasoning and a splash of water, simmer briefly.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Arrange rice in bowls and top with seasoned meat.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 4, text: 'Add lettuce, tomato and cheese on top and serve.', durationMinutes: 5, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 650,
      proteinGramsPerPortion: 28,
      fatGramsPerPortion: 26,
      carbsGramsPerPortion: 75,
    },
  },

  {
    id: 'seed-fusion-vegan-curry-noodle-soup-1',
    title: 'Vegan Curry Noodle Soup',
    description: 'Coconut curry soup with rice noodles and mixed vegetables.',
    diet: 'vegan',
    totalMinutes: 25,
    cuisine: 'fusion',
    likes: 44,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Rice noodles', quantity: 150, unit: 'g', isFromUser: false },
      { name: 'Coconut milk', quantity: 200, unit: 'ml', isFromUser: false },
      { name: 'Vegetable stock', quantity: 400, unit: 'ml', isFromUser: false },
      { name: 'Red curry paste', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Mixed vegetables (carrot, peas, pepper)', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Lime juice', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Soak or cook rice noodles according to package instructions.', durationMinutes: 10, assignedToHelper: 1 },
      { order: 2, text: 'Fry curry paste briefly in oil in a pot.', durationMinutes: 2, assignedToHelper: 2 },
      { order: 3, text: 'Add coconut milk and vegetable stock, bring to a simmer.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 4, text: 'Add vegetables and cook until just tender, then season with lime juice and salt.', durationMinutes: 6, assignedToHelper: 2 },
      { order: 5, text: 'Divide noodles into bowls and pour the soup over them.', durationMinutes: 2, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 540,
      proteinGramsPerPortion: 12,
      fatGramsPerPortion: 24,
      carbsGramsPerPortion: 70,
    },
  },

  {
    id: 'seed-fusion-keto-burger-bowl-1',
    title: 'Keto Burger Bowl',
    description: 'Burger components served in a bowl without the bun.',
    diet: 'keto',
    totalMinutes: 20,
    cuisine: 'fusion',
    likes: 42,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Ground beef', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Lettuce, chopped', quantity: 60, unit: 'g', isFromUser: false },
      { name: 'Tomato, diced', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Pickles, sliced', quantity: 30, unit: 'g', isFromUser: false },
      { name: 'Cheese slices', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Mayonnaise', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Mustard', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.25, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Form ground beef into patties, season with salt and pepper.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 2, text: 'Fry patties in oil until cooked to your liking, place cheese slices on top to melt.', durationMinutes: 8, assignedToHelper: 2 },
      { order: 3, text: 'Arrange lettuce, tomato and pickles in bowls.', durationMinutes: 3, assignedToHelper: 1 },
      { order: 4, text: 'Top with burger patties and drizzle with mayonnaise and mustard.', durationMinutes: 4, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 580,
      proteinGramsPerPortion: 34,
      fatGramsPerPortion: 44,
      carbsGramsPerPortion: 8,
    },
  },

  {
    id: 'seed-fusion-vegan-buddha-bowl-1',
    title: 'Vegan Buddha Bowl',
    description: 'Colorful bowl with grains, roasted vegetables and tahini dressing.',
    diet: 'vegan',
    totalMinutes: 30,
    cuisine: 'fusion',
    likes: 46,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Cooked quinoa or rice', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Chickpeas, drained', quantity: 120, unit: 'g', isFromUser: false },
      { name: 'Sweet potato, cubed', quantity: 150, unit: 'g', isFromUser: false },
      { name: 'Broccoli florets', quantity: 100, unit: 'g', isFromUser: false },
      { name: 'Tahini', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Lemon juice', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Black pepper', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Roast sweet potato and broccoli tossed in olive oil, salt and pepper at 200°C until tender.', durationMinutes: 20, assignedToHelper: 1 },
      { order: 2, text: 'Warm the chickpeas briefly in a pan or oven.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Whisk tahini, lemon juice, a little water and salt into a dressing.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 4, text: 'Arrange cooked quinoa or rice in bowls and top with vegetables and chickpeas, drizzle with dressing.', durationMinutes: 5, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 600,
      proteinGramsPerPortion: 20,
      fatGramsPerPortion: 24,
      carbsGramsPerPortion: 78,
    },
  },

  {
    id: 'seed-fusion-sushi-burrito-1',
    title: 'Sushi Burrito',
    description: 'Large nori wrap filled with rice, vegetables and fish or tofu.',
    diet: 'none',
    totalMinutes: 30,
    cuisine: 'fusion',
    likes: 40,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Sushi rice, cooked and seasoned', quantity: 200, unit: 'g', isFromUser: false },
      { name: 'Nori sheets', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Cucumber, strips', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Carrot, strips', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Avocado, sliced', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Smoked salmon or marinated tofu', quantity: 80, unit: 'g', isFromUser: false },
      { name: 'Soy sauce', quantity: 2, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Place a nori sheet shiny-side down on a mat.', durationMinutes: 2, assignedToHelper: 1 },
      { order: 2, text: 'Spread a thick layer of rice over most of the sheet, leaving one end free.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Arrange cucumber, carrot, avocado and fish or tofu in the center.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 4, text: 'Roll up tightly like a burrito and seal the edge with a little water.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 5, text: 'Cut in half and serve with soy sauce.', durationMinutes: 3, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 520,
      proteinGramsPerPortion: 20,
      fatGramsPerPortion: 16,
      carbsGramsPerPortion: 72,
    },
  },

  {
    id: 'seed-fusion-keto-zoodle-pesto-1',
    title: 'Keto Zoodle Pesto Bowl',
    description: 'Zucchini noodles with basil pesto and cherry tomatoes.',
    diet: 'keto',
    totalMinutes: 15,
    cuisine: 'fusion',
    likes: 37,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Zucchini, spiralized into noodles', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Basil pesto', quantity: 2, unit: 'tbsp', isFromUser: false },
      { name: 'Cherry tomatoes, halved', quantity: 80, unit: 'g', isFromUser: false },
      { name: 'Parmesan, grated', quantity: 20, unit: 'g', isFromUser: false },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Salt', quantity: 0.5, unit: 'tsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Sauté zoodles briefly in olive oil until just softened.', durationMinutes: 4, assignedToHelper: 1 },
      { order: 2, text: 'Toss with basil pesto off the heat.', durationMinutes: 3, assignedToHelper: 2 },
      { order: 3, text: 'Add cherry tomatoes and Parmesan, season with salt and serve.', durationMinutes: 5, assignedToHelper: 1 },
    ],
    nutrition: {
      energyKcalPerPortion: 280,
      proteinGramsPerPortion: 10,
      fatGramsPerPortion: 24,
      carbsGramsPerPortion: 6,
    },
  },

  {
    id: 'seed-fusion-vegan-pad-thai-style-1',
    title: 'Vegan Pad Thai-Style Noodles',
    description: 'Rice noodles with vegetables and a tangy peanut-tamarind sauce.',
    diet: 'vegan',
    totalMinutes: 25,
    cuisine: 'fusion',
    likes: 45,
    source: 'seed',
    createdAt: null,
    ingredients: [
      { name: 'Rice noodles', quantity: 150, unit: 'g', isFromUser: false },
      { name: 'Carrot, julienned', quantity: 1, unit: 'pcs', isFromUser: false },
      { name: 'Bell pepper, strips', quantity: 0.5, unit: 'pcs', isFromUser: false },
      { name: 'Spring onions, sliced', quantity: 2, unit: 'pcs', isFromUser: false },
      { name: 'Peanut butter', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Soy sauce', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Lime juice', quantity: 1, unit: 'tbsp', isFromUser: false },
      { name: 'Tamarind paste or sugar', quantity: 1, unit: 'tsp', isFromUser: false },
      { name: 'Oil', quantity: 1, unit: 'tbsp', isFromUser: false },
    ],
    steps: [
      { order: 1, text: 'Soak or cook rice noodles according to package instructions.', durationMinutes: 10, assignedToHelper: 1 },
      { order: 2, text: 'Stir-fry vegetables in oil in a large pan or wok.', durationMinutes: 5, assignedToHelper: 2 },
      { order: 3, text: 'Mix peanut butter, soy sauce, lime juice and tamarind or sugar with a little water to make a sauce.', durationMinutes: 5, assignedToHelper: 1 },
      { order: 4, text: 'Add noodles and sauce to the pan, toss well and heat through.', durationMinutes: 5, assignedToHelper: 2 },
    ],
    nutrition: {
      energyKcalPerPortion: 520,
      proteinGramsPerPortion: 14,
      fatGramsPerPortion: 18,
      carbsGramsPerPortion: 75,
    },
  },

];

